#!/usr/bin/env bash
#
# livedocs installer
# --------------------------------
# Self-contained bash installer that wires the "semantic feature" (skills +
# agent + Drupal doc adapter scripts) plus the generic core
# (livedocs.py) into your shell and your coding agent, on top of the
# codebase-memory-mcp knowledge-graph backend.
#
# UX mirrors codebase-memory-mcp's installer, but we are interpreted scripts,
# not a compiled binary, so everything lives in this one file.
#
# License: MIT (see plugin.json provenance in README). Author: gkastanis.
#
set -euo pipefail

# ---------------------------------------------------------------------------
# 0. Constants / repo self-location
# ---------------------------------------------------------------------------
# Resolve the directory this script lives in (the repo checkout) so we can copy
# assets out of it. Works whether invoked by path, by symlink, or via `bash`.
LIVEDOCS_SELF="${BASH_SOURCE[0]}"
while [ -h "$LIVEDOCS_SELF" ]; do
  _dir="$(cd -P "$(dirname "$LIVEDOCS_SELF")" >/dev/null 2>&1 && pwd)"
  LIVEDOCS_SELF="$(readlink "$LIVEDOCS_SELF")"
  case "$LIVEDOCS_SELF" in /*) ;; *) LIVEDOCS_SELF="$_dir/$LIVEDOCS_SELF" ;; esac
done
REPO_DIR="$(cd -P "$(dirname "$LIVEDOCS_SELF")" >/dev/null 2>&1 && pwd)"

# Asset sources within the repo checkout.
# EXTRACT-ONLY: today we copy from the repo's adapters/ + core/ checkout.
# TODO(release): swap these for a downloaded release tarball verified against a
#                published SHA256 (checksums.txt), the way codebase-memory-mcp
#                does for its binary, instead of copying from a working tree.
CORE_BRIDGE="$REPO_DIR/core/livedocs.py"
ADAPTER_DIR="$REPO_DIR/adapters/drupal"
ADAPTER_SKILLS_DIR="$ADAPTER_DIR/skills"
ADAPTER_AGENTS_DIR="$ADAPTER_DIR/agents"
ADAPTER_COMMANDS_DIR="$ADAPTER_DIR/commands"
ADAPTER_SCRIPTS_DIR="$ADAPTER_DIR/scripts"

# Skills we manage (installed into the agent's skills/ dir).
LIVEDOCS_SKILLS=(structural-index discover semantic-docs)
# Slash-commands we manage (installed into the agent's commands/ dir).
LIVEDOCS_COMMANDS=(drupal-semantic)
# Generic, adapter-independent slash-commands shipped from the repo's commands/.
GENERIC_COMMANDS_DIR="$REPO_DIR/commands"
LIVEDOCS_GENERIC_COMMANDS=(livedocs-check)
# Agent definitions we manage.
LIVEDOCS_AGENTS=(semantic-architect)

# Managed-region fences.
MD_START="<!-- livedocs:start -->"
MD_END="<!-- livedocs:end -->"
RC_START="# >>> livedocs >>>"
RC_END="# <<< livedocs <<<"
FILE_TAG="# Auto-generated by livedocs"

# codebase-memory-mcp upstream.
CBM_INSTALL_URL="https://raw.githubusercontent.com/DeusData/codebase-memory-mcp/main/install.sh"
CBM_REPO_URL="https://github.com/DeusData/codebase-memory-mcp"

# Drupal extension map applied to codebase-memory-mcp config.
read -r -d '' CBM_EXTRA_EXT_JSON <<'JSON' || true
{".module":"php",".install":"php",".inc":"php",".theme":"php",".engine":"php",".profile":"php",".phtml":"php",".twig":"html"}
JSON

# ---------------------------------------------------------------------------
# 1. Args
# ---------------------------------------------------------------------------
DRY=0
ASSUME=          # "" interactive, "y" yes, "n" no
SKIP_CONFIG=0
SKIP_AGENTS=0
FORCE=0
DO_UNINSTALL=0
PREFIX="${HOME}/.local"

usage() {
  cat <<EOF
livedocs installer

Usage: install.sh [options]

  --dry-run        Print actions without touching the filesystem.
  -y               Assume "yes" to prompts (default when non-interactive).
  -n               Assume "no" to prompts.
  --skip-config    Do not change codebase-memory-mcp config (extra_extensions, auto_index).
  --skip-agents    Do not wire skills/command/agent into your coding agent (CLI only).
  --prefix=DIR     Install prefix for bin/ and lib/ (default: ~/.local).
  --force          Reinstall even if nothing changed.
  --uninstall      Remove everything this installer placed (see uninstall.sh).
  -h, --help       Show this help.
EOF
}

for arg in "$@"; do
  case "$arg" in
    --dry-run)     DRY=1 ;;
    -y)            ASSUME=y ;;
    -n)            ASSUME=n ;;
    --skip-config) SKIP_CONFIG=1 ;;
    --skip-agents) SKIP_AGENTS=1 ;;
    --force)       FORCE=1 ;;
    --uninstall)   DO_UNINSTALL=1 ;;
    --prefix=*)    PREFIX="${arg#--prefix=}" ;;
    -h|--help)     usage; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; usage >&2; exit 2 ;;
  esac
done

# Non-tty defaults to -y (unattended, e.g. curl | bash).
if [ -z "$ASSUME" ] && [ ! -t 0 ]; then
  ASSUME=y
fi

# Expand a possible leading ~ in --prefix.
case "$PREFIX" in
  "~"|"~/"*) PREFIX="${HOME}${PREFIX#\~}" ;;
esac

BIN_DIR="$PREFIX/bin"
LIB_DIR="$PREFIX/lib/livedocs"

# ---------------------------------------------------------------------------
# 2. Output helpers + DRY guard
# ---------------------------------------------------------------------------
CHANGED=0   # set whenever a real (non-dry) mutation happens

info() { printf '  %s\n' "$*"; }
step() { printf '\n==> %s\n' "$*"; }
warn() { printf '  WARNING: %s\n' "$*" >&2; }

# ask <prompt> <default y|n> -> returns 0 for yes, 1 for no.
ask() {
  local prompt="$1" def="${2:-y}" reply
  if [ -n "$ASSUME" ]; then
    [ "$ASSUME" = y ] && return 0 || return 1
  fi
  if [ ! -t 0 ]; then
    [ "$def" = y ] && return 0 || return 1
  fi
  local hint="[Y/n]"; [ "$def" = n ] && hint="[y/N]"
  read -r -p "  $prompt $hint " reply || reply=""
  reply="${reply:-$def}"
  case "$reply" in [Yy]*) return 0 ;; *) return 1 ;; esac
}

# run <description> <cmd...> : the single DRY guard for every fs mutation.
# In dry-run, prints "would <description>" and does nothing. Otherwise runs the
# command and marks CHANGED.
run() {
  local desc="$1"; shift
  if [ "$DRY" -eq 1 ]; then
    printf '  would %s\n' "$desc"
    return 0
  fi
  "$@"
  CHANGED=1
}

# write_file <description> <path> : create a file from stdin via the DRY guard.
write_file() {
  local desc="$1" path="$2"
  if [ "$DRY" -eq 1 ]; then
    cat >/dev/null   # consume stdin so callers/heredocs don't block
    printf '  would %s\n' "$desc"
    return 0
  fi
  mkdir -p "$(dirname "$path")"
  cat >"$path"
  CHANGED=1
}

finish_dry() {
  if [ "$DRY" -eq 1 ]; then
    printf '\n(dry-run: no files were modified)\n'
    exit 0
  fi
}

# ---------------------------------------------------------------------------
# Uninstall delegation
# ---------------------------------------------------------------------------
if [ "$DO_UNINSTALL" -eq 1 ]; then
  UN="$REPO_DIR/uninstall.sh"
  if [ -f "$UN" ]; then
    flags=()
    [ "$DRY" -eq 1 ] && flags+=(--dry-run)
    [ "$ASSUME" = y ] && flags+=(-y)
    [ "$ASSUME" = n ] && flags+=(-n)
    flags+=("--prefix=$PREFIX")
    exec bash "$UN" "${flags[@]}"
  fi
  # Fallback: inline uninstall logic shares the same helpers below, but the
  # canonical implementation lives in uninstall.sh. If it's missing, bail.
  echo "uninstall.sh not found next to install.sh ($UN)" >&2
  exit 1
fi

# ===========================================================================
# INSTALL
# ===========================================================================
step "livedocs installer"
info "prefix:        $PREFIX"
info "bin:           $BIN_DIR"
info "lib:           $LIB_DIR"
[ "$DRY" -eq 1 ] && info "mode:          DRY-RUN (no filesystem changes)"

# ---------------------------------------------------------------------------
# 3. Prechecks: python3 >= 3.8 and git
# ---------------------------------------------------------------------------
step "Checking prerequisites"
if ! command -v python3 >/dev/null 2>&1; then
  echo "ERROR: python3 is required but not found on PATH." >&2
  exit 1
fi
if ! python3 - <<'PY'
import sys
sys.exit(0 if sys.version_info >= (3, 8) else 1)
PY
then
  echo "ERROR: python3 >= 3.8 is required (found $(python3 -V 2>&1))." >&2
  exit 1
fi
info "python3 OK ($(python3 -V 2>&1))"

if ! command -v git >/dev/null 2>&1; then
  echo "ERROR: git is required but not found on PATH." >&2
  exit 1
fi
info "git OK ($(git --version 2>&1))"

# ---------------------------------------------------------------------------
# 4. Ensure codebase-memory-mcp backend
# ---------------------------------------------------------------------------
step "Ensuring codebase-memory-mcp backend"
if command -v codebase-memory-mcp >/dev/null 2>&1; then
  ver="$(codebase-memory-mcp --version 2>&1 || echo '?')"
  info "codebase-memory-mcp present ($ver)"
else
  info "codebase-memory-mcp not found."
  if ask "Install codebase-memory-mcp from $CBM_REPO_URL now?" y; then
    if [ "$DRY" -eq 1 ]; then
      info "would download and run: curl -fsSL $CBM_INSTALL_URL | bash"
    else
      if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$CBM_INSTALL_URL" | bash
      elif command -v wget >/dev/null 2>&1; then
        wget -qO- "$CBM_INSTALL_URL" | bash
      else
        echo "ERROR: need curl or wget to install codebase-memory-mcp." >&2
        exit 1
      fi
      CHANGED=1
      command -v codebase-memory-mcp >/dev/null 2>&1 \
        && info "codebase-memory-mcp installed ($(codebase-memory-mcp --version 2>&1 || echo '?'))" \
        || warn "codebase-memory-mcp still not on PATH after install; check $CBM_REPO_URL"
    fi
  else
    warn "Skipping codebase-memory-mcp install; livedocs will not work until it is present."
  fi
fi

# ---------------------------------------------------------------------------
# 5. Apply Drupal cbm config (idempotent JSON merge)
# ---------------------------------------------------------------------------
step "Applying Drupal extra_extensions config"
CBM_CONFIG="$HOME/.config/codebase-memory-mcp/config.json"
if [ "$SKIP_CONFIG" -eq 1 ]; then
  info "Skipped (--skip-config)."
else
  if [ "$DRY" -eq 1 ]; then
    info "would merge extra_extensions into $CBM_CONFIG"
  else
    mkdir -p "$(dirname "$CBM_CONFIG")"
    # Idempotent merge: load-or-{}, setdefault extra_extensions, update, write
    # back only if changed. Never clobbers unrelated keys.
    out="$(CBM_CFG="$CBM_CONFIG" CBM_EXT="$CBM_EXTRA_EXT_JSON" python3 <<'PY'
import json, os, pathlib
p = pathlib.Path(os.environ["CBM_CFG"])
add = json.loads(os.environ["CBM_EXT"])
cfg = {}
if p.exists():
    try:
        cfg = json.loads(p.read_text() or "{}")
    except Exception:
        cfg = {}
ext = cfg.setdefault("extra_extensions", {})
before = dict(ext)
ext.update(add)
if ext == before:
    print("up to date")
else:
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(cfg, indent=2) + "\n")
    print("written")
PY
)"
    if [ "$out" = "up to date" ]; then
      info "extra_extensions already up to date."
    else
      info "extra_extensions merged into $CBM_CONFIG"
      CHANGED=1
    fi
  fi
fi

# ---------------------------------------------------------------------------
# 5b. Enable auto-index so the graph keeps itself fresh
# ---------------------------------------------------------------------------
step "Enabling codebase-memory-mcp auto-index"
if [ "$SKIP_CONFIG" -eq 1 ]; then
  info "Skipped (--skip-config)."
elif ! command -v codebase-memory-mcp >/dev/null 2>&1; then
  info "codebase-memory-mcp not on PATH; skipping (enable later with: codebase-memory-mcp config set auto_index true)."
elif codebase-memory-mcp config get auto_index 2>/dev/null | grep -qi true; then
  info "auto_index already enabled."
elif [ "$DRY" -eq 1 ]; then
  info "would enable auto_index (config set auto_index true; auto_index_limit 50000)"
else
  if codebase-memory-mcp config set auto_index true >/dev/null 2>&1 \
     && codebase-memory-mcp config set auto_index_limit 50000 >/dev/null 2>&1; then
    info "auto_index enabled; the graph re-indexes on git changes during an MCP session."
    CHANGED=1
  else
    warn "could not enable auto_index; run manually: codebase-memory-mcp config set auto_index true"
  fi
fi

# ---------------------------------------------------------------------------
# 6. Place assets (bin + lib)
# ---------------------------------------------------------------------------
step "Installing core and Drupal adapter scripts"

# 6a. livedocs core -> $BIN_DIR/livedocs (+x)
if [ ! -f "$CORE_BRIDGE" ]; then
  echo "ERROR: core not found at $CORE_BRIDGE" >&2
  exit 1
fi
BIN_BRIDGE="$BIN_DIR/livedocs"
if [ "$DRY" -eq 1 ]; then
  info "would install $CORE_BRIDGE -> $BIN_BRIDGE (chmod +x)"
elif [ "$FORCE" -eq 0 ] && [ -f "$BIN_BRIDGE" ] && cmp -s "$CORE_BRIDGE" "$BIN_BRIDGE"; then
  info "livedocs already up to date."
else
  mkdir -p "$BIN_DIR"
  cp "$CORE_BRIDGE" "$BIN_BRIDGE"
  chmod +x "$BIN_BRIDGE"
  CHANGED=1
  info "installed livedocs -> $BIN_BRIDGE"
fi

# 6b. Drupal adapter .sh generators/validators -> $LIB_DIR
if [ "$DRY" -eq 1 ]; then
  info "would install Drupal adapter scripts -> $LIB_DIR/"
else
  if [ ! -d "$ADAPTER_SCRIPTS_DIR" ]; then
    warn "adapter scripts dir not found ($ADAPTER_SCRIPTS_DIR); skipping lib install."
    warn "  (Lot 1 populates adapters/drupal/; re-run after assets are present.)"
  else
    mkdir -p "$LIB_DIR"
    n=0
    # Copy every .sh under the adapter scripts tree, preserving subpaths.
    while IFS= read -r -d '' f; do
      rel="${f#"$ADAPTER_SCRIPTS_DIR"/}"
      dest="$LIB_DIR/$rel"
      if [ "$FORCE" -eq 1 ] || [ ! -f "$dest" ] || ! cmp -s "$f" "$dest"; then
        mkdir -p "$(dirname "$dest")"
        cp "$f" "$dest"
        chmod +x "$dest" 2>/dev/null || true
        CHANGED=1
        n=$((n + 1))
      fi
    done < <(find "$ADAPTER_SCRIPTS_DIR" -type f -name '*.sh' -print0)
    if [ "$n" -gt 0 ]; then
      info "installed/updated $n adapter script(s) -> $LIB_DIR/"
    else
      info "adapter scripts already up to date."
    fi
  fi
fi

# 6c. Verify livedocs is invocable.
# NOTE: livedocs.py takes POSITIONAL args (anchor|check|enrich <sem_dir>
# <project>) and has no --help; `--help` is not a real subcommand, so a nonzero
# exit is expected. We only assert the file execs under python3 (syntax + shebang
# resolve) rather than demanding exit 0. This honours the read-only core.
step "Verifying livedocs"
if [ "$DRY" -eq 1 ]; then
  info "would verify: livedocs --help"
else
  if [ -x "$BIN_BRIDGE" ]; then
    if "$BIN_BRIDGE" --help >/dev/null 2>&1; then
      info "livedocs --help exited 0."
    else
      # Expected: positional CLI has no --help. Confirm the file at least parses.
      if python3 -c "import py_compile,sys; py_compile.compile('$BIN_BRIDGE', doraise=True)" 2>/dev/null; then
        info "livedocs installed and parses OK (positional CLI: anchor|check|enrich)."
      else
        warn "livedocs failed to compile under python3."
      fi
    fi
  else
    info "(dry-run or not installed) skipping livedocs verify."
  fi
fi

# ---------------------------------------------------------------------------
# 7. PATH wiring
# ---------------------------------------------------------------------------
step "Wiring PATH"
detect_rc() {
  # Pick the user's interactive-shell rc file.
  local shell_base; shell_base="$(basename "${SHELL:-}")"
  case "$shell_base" in
    zsh)  echo "$HOME/.zshrc" ;;
    bash) if [ -f "$HOME/.bashrc" ]; then echo "$HOME/.bashrc"; else echo "$HOME/.bash_profile"; fi ;;
    *)    if [ -f "$HOME/.bashrc" ]; then echo "$HOME/.bashrc"; else echo "$HOME/.profile"; fi ;;
  esac
}
RC_FILE="$(detect_rc)"
PATH_LINE="export PATH=\"$BIN_DIR:\$PATH\""

if [ "$DRY" -eq 1 ]; then
  info "would ensure PATH block in $RC_FILE"
else
  if [ -f "$RC_FILE" ] && grep -qF "$RC_START" "$RC_FILE"; then
    # Block exists: rewrite its contents (idempotent / --force safe).
    tmp="$(mktemp)"
    awk -v s="$RC_START" -v e="$RC_END" -v line="$PATH_LINE" '
      $0==s {print; print line; skip=1; next}
      $0==e {skip=0; print; next}
      skip!=1 {print}
    ' "$RC_FILE" >"$tmp"
    if cmp -s "$tmp" "$RC_FILE"; then
      info "PATH block already current in $RC_FILE"
      rm -f "$tmp"
    else
      cat "$tmp" >"$RC_FILE"; rm -f "$tmp"
      CHANGED=1
      info "refreshed PATH block in $RC_FILE"
    fi
  else
    mkdir -p "$(dirname "$RC_FILE")"
    {
      printf '\n%s\n' "$RC_START"
      printf '%s\n' "$PATH_LINE"
      printf '%s\n' "$RC_END"
    } >>"$RC_FILE"
    CHANGED=1
    info "added PATH block to $RC_FILE"
  fi
fi

# ---------------------------------------------------------------------------
# 8. Agent wiring
# ---------------------------------------------------------------------------
step "Wiring coding agents"

if [ "$SKIP_AGENTS" -eq 1 ]; then
  info "Skipped (--skip-agents); the livedocs command-line tool is still installed."
else

# --- Claude Code ---
if [ -d "$HOME/.claude" ] || [ -f "$HOME/.claude.json" ]; then
  info "Claude Code: detected."
  CLAUDE_SKILLS="$HOME/.claude/skills"
  CLAUDE_AGENTS="$HOME/.claude/agents"

  # Skills (whole directories copied from the adapter). Each managed file gets
  # the file-level tag prepended unless it is itself a multi-file skill payload
  # we copy verbatim; we tag the SKILL.md as the managed marker.
  if [ ! -d "$ADAPTER_SKILLS_DIR" ]; then
    warn "  adapter skills dir not found ($ADAPTER_SKILLS_DIR); skipping skill install."
  else
    for sk in "${LIVEDOCS_SKILLS[@]}"; do
      src="$ADAPTER_SKILLS_DIR/$sk"
      dest="$CLAUDE_SKILLS/$sk"
      if [ ! -d "$src" ]; then
        warn "  skill '$sk' missing in adapter ($src); skipped."
        continue
      fi
      if [ "$DRY" -eq 1 ]; then
        info "  would install skill: $sk -> $dest"
        continue
      fi
      if [ "$FORCE" -eq 0 ] && [ -d "$dest" ] && [ -f "$dest/.livedocs-managed" ] \
         && diff -rq -x '.livedocs-managed' "$src" "$dest" >/dev/null 2>&1; then
        info "  skill '$sk' already up to date."
        continue
      fi
      # Refuse to clobber a same-named skill we did not install (no marker).
      if [ -d "$dest" ] && [ ! -f "$dest/.livedocs-managed" ]; then
        warn "  skill '$sk' at $dest exists but is not ours; leaving it untouched."
        continue
      fi
      # UPSERT: clear our prior copy, then re-copy (never duplicates).
      rm -rf "$dest"
      mkdir -p "$(dirname "$dest")"
      cp -R "$src" "$dest"
      # Provenance marker so uninstall only removes skills we created.
      printf '%s\n' "$FILE_TAG" >"$dest/.livedocs-managed"
      CHANGED=1
      info "  installed skill: $sk"
    done
  fi

  # Agents (single markdown files). Tag the whole generated file.
  if [ ! -d "$ADAPTER_AGENTS_DIR" ]; then
    warn "  adapter agents dir not found ($ADAPTER_AGENTS_DIR); skipping agent install."
  else
    for ag in "${LIVEDOCS_AGENTS[@]}"; do
      src="$ADAPTER_AGENTS_DIR/$ag.md"
      dest="$CLAUDE_AGENTS/$ag.md"
      if [ ! -f "$src" ]; then
        warn "  agent '$ag' missing in adapter ($src); skipped."
        continue
      fi
      if [ "$DRY" -eq 1 ]; then
        info "  would install agent: $ag -> $dest"
        continue
      fi
      # Build tagged content (faithful copy + a leading provenance tag line).
      tmp="$(mktemp)"
      { printf '%s\n' "$FILE_TAG"; cat "$src"; } >"$tmp"
      if [ "$FORCE" -eq 0 ] && [ -f "$dest" ] && cmp -s "$tmp" "$dest"; then
        info "  agent '$ag' already up to date."
        rm -f "$tmp"
        continue
      fi
      mkdir -p "$(dirname "$dest")"
      cat "$tmp" >"$dest"; rm -f "$tmp"
      CHANGED=1
      info "  installed agent: $ag"
    done
  fi

  # Slash-commands (single markdown files). Tag the whole generated file.
  CLAUDE_COMMANDS="$HOME/.claude/commands"
  if [ ! -d "$ADAPTER_COMMANDS_DIR" ]; then
    warn "  adapter commands dir not found ($ADAPTER_COMMANDS_DIR); skipping command install."
  else
    for cmd in "${LIVEDOCS_COMMANDS[@]}"; do
      src="$ADAPTER_COMMANDS_DIR/$cmd.md"
      dest="$CLAUDE_COMMANDS/$cmd.md"
      if [ ! -f "$src" ]; then
        warn "  command '$cmd' missing in adapter ($src); skipped."
        continue
      fi
      if [ "$DRY" -eq 1 ]; then
        info "  would install command: $cmd -> $dest"
        continue
      fi
      tmp="$(mktemp)"
      { printf '%s\n' "$FILE_TAG"; cat "$src"; } >"$tmp"
      if [ "$FORCE" -eq 0 ] && [ -f "$dest" ] && cmp -s "$tmp" "$dest"; then
        info "  command '$cmd' already up to date."
        rm -f "$tmp"
        continue
      fi
      mkdir -p "$(dirname "$dest")"
      cat "$tmp" >"$dest"; rm -f "$tmp"
      CHANGED=1
      info "  installed command: $cmd"
    done
  fi

  # Generic (adapter-independent) slash-commands, tagged the same way.
  if [ -d "$GENERIC_COMMANDS_DIR" ]; then
    for cmd in "${LIVEDOCS_GENERIC_COMMANDS[@]}"; do
      src="$GENERIC_COMMANDS_DIR/$cmd.md"
      dest="$CLAUDE_COMMANDS/$cmd.md"
      [ -f "$src" ] || { warn "  command '$cmd' missing ($src); skipped."; continue; }
      if [ "$DRY" -eq 1 ]; then
        info "  would install command: $cmd -> $dest"
        continue
      fi
      tmp="$(mktemp)"
      { printf '%s\n' "$FILE_TAG"; cat "$src"; } >"$tmp"
      if [ "$FORCE" -eq 0 ] && [ -f "$dest" ] && cmp -s "$tmp" "$dest"; then
        info "  command '$cmd' already up to date."
        rm -f "$tmp"
        continue
      fi
      mkdir -p "$(dirname "$dest")"
      cat "$tmp" >"$dest"; rm -f "$tmp"
      CHANGED=1
      info "  installed command: $cmd"
    done
  fi
else
  info "Claude Code: not detected (skipped)."
fi

# --- Other agents: detected-but-not-yet-supported no-ops ---
if [ -d "$HOME/.codex" ] || [ -f "$HOME/.codex.json" ]; then
  info "Codex: detected, not yet supported (no-op)."
fi
if [ -d "$HOME/.gemini" ] || [ -f "$HOME/.config/gemini" ]; then
  info "Gemini: detected, not yet supported (no-op)."
fi
if [ -d "$HOME/.config/zed" ] || [ -d "$HOME/.zed" ]; then
  info "Zed: detected, not yet supported (no-op)."
fi

fi   # end --skip-agents guard

# ---------------------------------------------------------------------------
# 9. Finish
# ---------------------------------------------------------------------------
finish_dry

step "Done"
if [ "$CHANGED" -eq 0 ] && [ "$FORCE" -eq 0 ]; then
  echo "Already installed (nothing changed). Use --force to reinstall."
else
  echo "Installation complete."
  case ":${PATH}:" in
    *":$BIN_DIR:"*) ;;
    *) info "Open a new shell or 'source $RC_FILE' to pick up $BIN_DIR on PATH." ;;
  esac
fi
