#!/usr/bin/env bash
#
# semantic-graph-bridge uninstaller
# ---------------------------------
# Reverses every step install.sh performed:
#   - removes our skill + agent files from the agent config
#   - strips the managed PATH block from the shell rc
#   - removes $PREFIX/bin/cbm_bridge and $PREFIX/lib/semantic-graph-bridge
#   - OFFERS (default keep) to revert the Drupal extra_extensions config
#
# DATA SAFETY:
#   - NEVER deletes user .anchors.json sidecars (they are user data / git-tracked).
#   - NEVER removes codebase-memory-mcp or its indexes.
#   - Only OFFERS to revert our extra_extensions additions (prompt, default keep).
#
set -euo pipefail

# ---------------------------------------------------------------------------
# Self-location
# ---------------------------------------------------------------------------
SGB_SELF="${BASH_SOURCE[0]}"
while [ -h "$SGB_SELF" ]; do
  _dir="$(cd -P "$(dirname "$SGB_SELF")" >/dev/null 2>&1 && pwd)"
  SGB_SELF="$(readlink "$SGB_SELF")"
  case "$SGB_SELF" in /*) ;; *) SGB_SELF="$_dir/$SGB_SELF" ;; esac
done
REPO_DIR="$(cd -P "$(dirname "$SGB_SELF")" >/dev/null 2>&1 && pwd)"

SGB_SKILLS=(structural-index discover semantic-docs)
SGB_COMMANDS=(drupal-semantic)
SGB_AGENTS=(semantic-architect)

RC_START="# >>> semantic-graph-bridge >>>"
RC_END="# <<< semantic-graph-bridge <<<"
FILE_TAG="# Auto-generated by semantic-graph-bridge"

# Drupal extension map we may have added (for the revert offer).
read -r -d '' CBM_EXTRA_EXT_JSON <<'JSON' || true
{".module":"php",".install":"php",".inc":"php",".theme":"php",".engine":"php",".profile":"php",".phtml":"php",".twig":"html"}
JSON

# ---------------------------------------------------------------------------
# Args
# ---------------------------------------------------------------------------
DRY=0
ASSUME=
PREFIX="${HOME}/.local"

usage() {
  cat <<EOF
semantic-graph-bridge uninstaller

Usage: uninstall.sh [options]

  --dry-run        Print actions without touching the filesystem.
  -y               Assume "yes" to prompts (default when non-interactive).
  -n               Assume "no" to prompts.
  --prefix=DIR     Install prefix used at install time (default: ~/.local).
  -h, --help       Show this help.
EOF
}

for arg in "$@"; do
  case "$arg" in
    --dry-run)  DRY=1 ;;
    -y)         ASSUME=y ;;
    -n)         ASSUME=n ;;
    --prefix=*) PREFIX="${arg#--prefix=}" ;;
    -h|--help)  usage; exit 0 ;;
    *) echo "Unknown option: $arg" >&2; usage >&2; exit 2 ;;
  esac
done

if [ -z "$ASSUME" ] && [ ! -t 0 ]; then
  ASSUME=y
fi
case "$PREFIX" in
  "~"|"~/"*) PREFIX="${HOME}${PREFIX#\~}" ;;
esac

BIN_DIR="$PREFIX/bin"
LIB_DIR="$PREFIX/lib/semantic-graph-bridge"
BIN_BRIDGE="$BIN_DIR/cbm_bridge"

# ---------------------------------------------------------------------------
# Helpers + DRY guard
# ---------------------------------------------------------------------------
CHANGED=0
info() { printf '  %s\n' "$*"; }
step() { printf '\n==> %s\n' "$*"; }
warn() { printf '  WARNING: %s\n' "$*" >&2; }

ask() {
  local prompt="$1" def="${2:-y}" reply
  if [ -n "$ASSUME" ]; then
    [ "$ASSUME" = y ] && return 0 || return 1
  fi
  if [ ! -t 0 ]; then
    [ "$def" = y ] && return 0 || return 1
  fi
  local hint="[Y/n]"; [ "$def" = n ] && hint="[y/N]"
  read -r -p "  $prompt $hint " reply || reply=""
  reply="${reply:-$def}"
  case "$reply" in [Yy]*) return 0 ;; *) return 1 ;; esac
}

# rm_path <description> <path> : remove a file/dir through the DRY guard.
rm_path() {
  local desc="$1" path="$2"
  if [ ! -e "$path" ]; then
    return 0
  fi
  if [ "$DRY" -eq 1 ]; then
    printf '  would remove %s (%s)\n' "$desc" "$path"
    return 0
  fi
  rm -rf "$path"
  CHANGED=1
  info "removed $desc"
}

# ===========================================================================
# UNINSTALL
# ===========================================================================
step "semantic-graph-bridge uninstaller"
info "prefix: $PREFIX"
[ "$DRY" -eq 1 ] && info "mode:   DRY-RUN (no filesystem changes)"

# --- 1. Agent files (Claude Code) ---
step "Removing agent assets"
if [ -d "$HOME/.claude" ] || [ -f "$HOME/.claude.json" ]; then
  CLAUDE_SKILLS="$HOME/.claude/skills"
  CLAUDE_AGENTS="$HOME/.claude/agents"
  for sk in "${SGB_SKILLS[@]}"; do
    dest="$CLAUDE_SKILLS/$sk"
    # Only remove skills we installed (carry our provenance marker). A same-named
    # skill from another source (e.g. the drupal-workflow plugin) is left alone.
    if [ -d "$dest" ]; then
      if [ -f "$dest/.sgb-managed" ]; then
        rm_path "skill '$sk'" "$dest"
      else
        warn "skill '$sk' at $dest is not ours (no marker); leaving it untouched."
      fi
    fi
  done
  for ag in "${SGB_AGENTS[@]}"; do
    dest="$CLAUDE_AGENTS/$ag.md"
    # Only remove agent files we generated (tagged). Leave foreign files alone.
    if [ -f "$dest" ]; then
      if head -n1 "$dest" 2>/dev/null | grep -qF "$FILE_TAG"; then
        rm_path "agent '$ag'" "$dest"
      else
        warn "agent '$ag' at $dest is not tagged by us; leaving it untouched."
      fi
    fi
  done
  CLAUDE_COMMANDS="$HOME/.claude/commands"
  for cmd in "${SGB_COMMANDS[@]}"; do
    dest="$CLAUDE_COMMANDS/$cmd.md"
    # Only remove command files we generated (tagged). Leave foreign files alone.
    if [ -f "$dest" ]; then
      if head -n1 "$dest" 2>/dev/null | grep -qF "$FILE_TAG"; then
        rm_path "command '$cmd'" "$dest"
      else
        warn "command '$cmd' at $dest is not tagged by us; leaving it untouched."
      fi
    fi
  done
else
  info "Claude Code not detected; nothing to remove."
fi

# --- 2. PATH block ---
step "Stripping PATH block"
detect_rc_candidates() {
  printf '%s\n' "$HOME/.zshrc" "$HOME/.bashrc" "$HOME/.bash_profile" "$HOME/.profile"
}
while IFS= read -r rc; do
  [ -f "$rc" ] || continue
  grep -qF "$RC_START" "$rc" || continue
  if [ "$DRY" -eq 1 ]; then
    info "would strip PATH block from $rc"
    continue
  fi
  tmp="$(mktemp)"
  # Strip START..END, and also drop blank line(s) immediately preceding the block
  # (install.sh prepends one). Blank lines are buffered and re-emitted before the
  # next real line, but discarded when that next line is our START marker.
  awk -v s="$RC_START" -v e="$RC_END" '
    $0==s {skip=1; blank=0; next}
    $0==e {skip=0; next}
    skip==1 {next}
    /^[[:space:]]*$/ {blank++; next}
    {while (blank>0){print ""; blank--} print}
    END {while (blank>0){print ""; blank--}}
  ' "$rc" >"$tmp"
  cat "$tmp" >"$rc"; rm -f "$tmp"
  CHANGED=1
  info "stripped PATH block from $rc"
done < <(detect_rc_candidates)

# --- 3. bin + lib ---
step "Removing installed files"
rm_path "cbm_bridge" "$BIN_BRIDGE"
rm_path "lib dir" "$LIB_DIR"

# --- 4. Offer to revert extra_extensions (default keep) ---
step "Drupal extra_extensions config"
CBM_CONFIG="$HOME/.config/codebase-memory-mcp/config.json"
if [ -f "$CBM_CONFIG" ]; then
  if ask "Revert the Drupal extra_extensions we added in $CBM_CONFIG?" n; then
    if [ "$DRY" -eq 1 ]; then
      info "would remove our extra_extensions keys from $CBM_CONFIG"
    else
      CBM_CFG="$CBM_CONFIG" CBM_EXT="$CBM_EXTRA_EXT_JSON" python3 <<'PY'
import json, os, pathlib
p = pathlib.Path(os.environ["CBM_CFG"])
add = json.loads(os.environ["CBM_EXT"])
try:
    cfg = json.loads(p.read_text() or "{}")
except Exception:
    cfg = {}
ext = cfg.get("extra_extensions", {})
# Only remove keys whose value still matches what we set (don't clobber edits).
for k, v in add.items():
    if ext.get(k) == v:
        ext.pop(k, None)
if ext:
    cfg["extra_extensions"] = ext
else:
    cfg.pop("extra_extensions", None)
p.write_text(json.dumps(cfg, indent=2) + "\n")
print("reverted")
PY
      CHANGED=1
      info "reverted our extra_extensions entries (other keys preserved)."
    fi
  else
    info "Keeping extra_extensions (default)."
  fi
else
  info "No cbm config present; nothing to revert."
fi

# --- Data-safety reminders ---
step "Data safety"
info "Left untouched: codebase-memory-mcp, its indexes, and any .anchors.json sidecars."

echo
if [ "$DRY" -eq 1 ]; then
  echo "(dry-run — no files were modified)"
else
  echo "Uninstall complete."
fi
