#!/bin/bash
# generate-dependency-graph.sh - Cross-reference structural index files
# Output: docs/semantic/DEPENDENCY_GRAPH.md
# Reads structural/*.md to build service dependency chains, event/hook analysis,
# entity cross-references, and external boundaries.
set -e

PROJECT_DIR="${1:-${CLAUDE_PROJECT_DIR:-$(pwd)}}"
DOCS_DIR="$PROJECT_DIR/docs/semantic"
STRUCTURAL_DIR="$DOCS_DIR/structural"
TECH_DIR="$DOCS_DIR/tech"
OUTPUT="$DOCS_DIR/DEPENDENCY_GRAPH.md"

SERVICES_MD="$STRUCTURAL_DIR/services.md"
HOOKS_MD="$STRUCTURAL_DIR/hooks.md"
ROUTES_MD="$STRUCTURAL_DIR/routes.md"
PLUGINS_MD="$STRUCTURAL_DIR/plugins.md"
ENTITIES_MD="$STRUCTURAL_DIR/entities.md"

TMPOUT=$(mktemp)
trap 'rm -f "$TMPOUT"' EXIT

cat > "$TMPOUT" << HEADER
# Dependency Graph
<!-- Auto-generated by generate-dependency-graph.sh — do not edit manually -->
Generated: $(date -Iseconds)

HEADER

# --- Service Dependencies ---
echo "## Service Dependencies" >> "$TMPOUT"
echo "" >> "$TMPOUT"

if [[ -f "$SERVICES_MD" ]]; then
    echo "Services that inject other services (who-depends-on-whom):" >> "$TMPOUT"
    echo "" >> "$TMPOUT"
    echo '```' >> "$TMPOUT"

    # Parse the services.md table: extract service ID and its dependencies
    while IFS='|' read -r _ svc_id _ deps _ _ _; do
        svc_id=$(echo "$svc_id" | sed 's/`//g' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
        deps=$(echo "$deps" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')

        if [[ -n "$svc_id" && "$deps" != "-" && -n "$deps" && "$svc_id" != "Service ID" && ! "$svc_id" =~ ^-+$ ]]; then
            echo "$svc_id -> $deps" >> "$TMPOUT"
        fi
    done < <(grep '^|' "$SERVICES_MD" 2>/dev/null | tail -n +3)

    echo '```' >> "$TMPOUT"
    echo "" >> "$TMPOUT"

    # Most-depended-on services
    echo "### Most Injected Services (hotspots)" >> "$TMPOUT"
    echo "" >> "$TMPOUT"
    grep '^|' "$SERVICES_MD" 2>/dev/null | tail -n +3 | \
        sed 's/|/\n/g' | grep '@' | tr ',' '\n' | \
        sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//' | \
        grep -E '^@' | sort | uniq -c | sort -rn | head -15 | \
        while read -r count svc; do
            echo "- **$svc** (injected $count times)" >> "$TMPOUT"
        done
    echo "" >> "$TMPOUT"
else
    echo "_No services.md found. Run generate-service-graph.sh first._" >> "$TMPOUT"
    echo "" >> "$TMPOUT"
fi

# --- Event/Hook Chains ---
echo "## Event & Hook Chains" >> "$TMPOUT"
echo "" >> "$TMPOUT"

if [[ -f "$HOOKS_MD" ]]; then
    echo "### Hook implementations by hook name" >> "$TMPOUT"
    echo "" >> "$TMPOUT"

    # Group hooks by name
    grep '^|' "$HOOKS_MD" 2>/dev/null | tail -n +3 | \
        while IFS='|' read -r _ hook_name impl hook_type file module _; do
            hook_name=$(echo "$hook_name" | sed 's/`//g' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
            [[ -n "$hook_name" && ! "$hook_name" =~ ^-+$ && "$hook_name" != "Hook Name" ]] && echo "$hook_name"
        done | sort | uniq -c | sort -rn | head -20 | \
        while read -r count hook; do
            echo "- **$hook** ($count implementations)" >> "$TMPOUT"
        done
    echo "" >> "$TMPOUT"

    # Event subscribers from services
    if [[ -f "$SERVICES_MD" ]]; then
        echo "### Event Subscribers (from services.md)" >> "$TMPOUT"
        echo "" >> "$TMPOUT"
        if grep -qiE 'event_subscriber|event\.subscriber' "$SERVICES_MD" 2>/dev/null; then
            grep -iE 'event_subscriber|event\.subscriber' "$SERVICES_MD" | head -20 >> "$TMPOUT"
        else
            echo "_None found._" >> "$TMPOUT"
        fi
        echo "" >> "$TMPOUT"
    fi
else
    echo "_No hooks.md found. Run generate-hook-registry.sh first._" >> "$TMPOUT"
    echo "" >> "$TMPOUT"
fi

# --- Entity Cross-References ---
echo "## Entity Cross-References" >> "$TMPOUT"
echo "" >> "$TMPOUT"

if [[ -f "$ENTITIES_MD" ]]; then
    echo "### Declared entity types" >> "$TMPOUT"
    echo "" >> "$TMPOUT"
    grep '^|' "$ENTITIES_MD" 2>/dev/null | tail -n +3 | \
        while IFS='|' read -r _ etype eid _ _ _ _; do
            eid=$(echo "$eid" | sed 's/`//g' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
            etype=$(echo "$etype" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
            if [[ -n "$eid" && "$eid" != "ID" && ! "$eid" =~ ^-+$ ]]; then
                echo "- **$eid** ($etype)" >> "$TMPOUT"
            fi
        done
    echo "" >> "$TMPOUT"

    # Find entity_reference fields in config YAML
    echo "### Entity Reference Fields (from config YAML)" >> "$TMPOUT"
    echo "" >> "$TMPOUT"
    REF_COUNT=0
    FIND_DIRS=()
    for d in "$PROJECT_DIR/web/modules/custom" "$PROJECT_DIR/www/modules/custom" "$PROJECT_DIR/modules/custom" "$PROJECT_DIR/config"; do
        [[ -d "$d" ]] && FIND_DIRS+=("$d")
    done
    if [[ ${#FIND_DIRS[@]} -gt 0 ]]; then
        while IFS= read -r config_file; do
            REL_PATH="${config_file#$PROJECT_DIR/}"
            while IFS= read -r ref_line; do
                echo "- \`$REL_PATH\`: $ref_line" >> "$TMPOUT"
                ((REF_COUNT++)) || true
            done < <(grep -i "entity_reference\|target_type" "$config_file" 2>/dev/null | head -5)
        done < <(find -L "${FIND_DIRS[@]}" -name "*.yml" 2>/dev/null | head -100)
    fi

    if [[ "$REF_COUNT" -eq 0 ]]; then
        echo "_No entity_reference fields found in config YAML._" >> "$TMPOUT"
    fi
    echo "" >> "$TMPOUT"
else
    echo "_No entities.md found. Run generate-entity-map.sh first._" >> "$TMPOUT"
    echo "" >> "$TMPOUT"
fi

# --- External Boundaries ---
echo "## External Boundaries" >> "$TMPOUT"
echo "" >> "$TMPOUT"
echo "Services that inject external-facing dependencies:" >> "$TMPOUT"
echo "" >> "$TMPOUT"

EXTERNAL_COUNT=0
if [[ -f "$SERVICES_MD" ]]; then
    # External-facing dependency patterns (network, mail, queue — not cache/logger which are internal)
    # Note: grep -E uses | for alternation, not \|
    while IFS='|' read -r _ svc_id _ deps _ _ _; do
        svc_id=$(echo "$svc_id" | sed 's/`//g' | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')
        deps=$(echo "$deps" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')

        [[ -z "$svc_id" || "$svc_id" == "Service ID" || "$svc_id" =~ ^-+$ ]] && continue
        [[ "$deps" == "-" || -z "$deps" ]] && continue

        # Check for external-facing dependencies
        EXT_DEPS=""
        if echo "$deps" | grep -qE '@http_client|@guzzle'; then
            EXT_DEPS="${EXT_DEPS:+$EXT_DEPS, }HTTP client"
        fi
        if echo "$deps" | grep -qE '@plugin\.manager\.mail|@mailer|@mail_manager'; then
            EXT_DEPS="${EXT_DEPS:+$EXT_DEPS, }mail"
        fi
        if echo "$deps" | grep -qE '@queue|@queue_factory'; then
            EXT_DEPS="${EXT_DEPS:+$EXT_DEPS, }queue"
        fi
        if echo "$deps" | grep -qE '@key\.repository'; then
            EXT_DEPS="${EXT_DEPS:+$EXT_DEPS, }key storage"
        fi
        if echo "$deps" | grep -qE '@messenger|@event_dispatcher'; then
            EXT_DEPS="${EXT_DEPS:+$EXT_DEPS, }messaging"
        fi

        if [[ -n "$EXT_DEPS" ]]; then
            echo "- **\`$svc_id\`**: $EXT_DEPS" >> "$TMPOUT"
            ((EXTERNAL_COUNT++)) || true
        fi
    done < <(grep '^|' "$SERVICES_MD" 2>/dev/null | tail -n +3)
fi

if [[ "$EXTERNAL_COUNT" -eq 0 ]]; then
    echo "_No external-facing services detected._" >> "$TMPOUT"
fi
echo "" >> "$TMPOUT"

# --- Feature Adjacency Matrix ---
echo "## Feature Adjacency" >> "$TMPOUT"
echo "" >> "$TMPOUT"

if [[ -d "$TECH_DIR" ]]; then
    shopt -s nullglob
    tech_files=("$TECH_DIR"/*.md)
    FEATURE_COUNT=${#tech_files[@]}
    shopt -u nullglob
    if [[ "$FEATURE_COUNT" -le 15 ]]; then
        echo "Features that share services or modules:" >> "$TMPOUT"
        echo "" >> "$TMPOUT"

        # For each tech spec, find referenced modules/services
        for tech_file in "$TECH_DIR"/*.md; do
            [[ -f "$tech_file" ]] || continue
            FEATURE=$(basename "$tech_file" .md | sed 's/_[0-9]*_.*$//' | sed 's/-[0-9]*-.*$//' | tr '[:lower:]' '[:upper:]')

            # Find module names referenced in the spec
            MODULES=$(grep -oE '[a-z_]+_module\b|[a-z_]{3,}\.service\b' "$tech_file" 2>/dev/null | sort -u | head -10 | tr '\n' ', ' | sed 's/,$//')
            if [[ -n "$MODULES" ]]; then
                echo "- **$FEATURE**: $MODULES" >> "$TMPOUT"
            fi
        done
        echo "" >> "$TMPOUT"
    else
        echo "_$FEATURE_COUNT features found — adjacency matrix omitted (threshold: 15). Use \`discover deps:FEATURE\` for targeted analysis._" >> "$TMPOUT"
        echo "" >> "$TMPOUT"
    fi
else
    echo "_No tech specs found for adjacency analysis._" >> "$TMPOUT"
    echo "" >> "$TMPOUT"
fi

echo "---" >> "$TMPOUT"
echo "_Cross-reference generated from structural index files._" >> "$TMPOUT"

mv "$TMPOUT" "$OUTPUT"
echo "  DEPENDENCY_GRAPH.md generated"
