#!/bin/bash
# generate-base-fields.sh - Parse PHP baseFieldDefinitions() and entity attributes
# Output: docs/semantic/schemas/*.base-fields.json, docs/semantic/structural/base-fields.md
# Patches: docs/semantic/structural/entities.md (updates Fields column with base+config counts)
#
# Known limitations:
#   - parent::baseFieldDefinitions() provides implicit id/uuid/langcode — noted but not enumerated
#   - Config entities may lack baseFieldDefinitions() — skipped gracefully
#   - setDisplayOptions/setDisplayConfigurable are skipped (UI-only metadata)
set -e

PROJECT_DIR="${1:-${CLAUDE_PROJECT_DIR:-$(pwd)}}"
STRUCTURAL_DIR="$PROJECT_DIR/docs/semantic/structural"
SCHEMA_DIR="$PROJECT_DIR/docs/semantic/schemas"
ENTITIES_FILE="$STRUCTURAL_DIR/entities.md"

mkdir -p "$SCHEMA_DIR"
mkdir -p "$STRUCTURAL_DIR"

# --- Helpers ---

json_escape() {
    local s="$1"
    s="${s//\\/\\\\}"
    s="${s//\"/\\\"}"
    s="${s//$'\n'/\\n}"
    s="${s//$'\t'/\\t}"
    printf '%s' "$s"
}

# Extract a single-quoted value after a key from a string
# Usage: extract_sq_val "key" "$string"
extract_sq_val() {
    echo "$2" | grep -oE "$1:[[:space:]]*'[^']*'" | head -1 | sed "s/$1:[[:space:]]*'//;s/'$//"
}

# Extract a double-quoted value after a key from a string
extract_dq_val() {
    echo "$2" | grep -oE "$1:[[:space:]]*\"[^\"]*\"" | head -1 | sed "s/$1:[[:space:]]*\"//;s/\"$//"
}

# --- Find entity PHP files ---

MODULES_DIR=""
for search_dir in "$PROJECT_DIR/web/modules/custom" "$PROJECT_DIR/www/modules/custom" "$PROJECT_DIR/modules/custom"; do
    if [[ -d "$search_dir" ]]; then
        MODULES_DIR="$search_dir"
        break
    fi
done

if [[ -z "$MODULES_DIR" ]]; then
    echo "  base-fields: No custom modules directory found"
    exit 0
fi

# Find PHP files that contain both entity type declarations AND baseFieldDefinitions
ENTITY_FILES=()
while IFS= read -r f; do
    if grep -qE '#\[(Content|Config)EntityType' "$f" 2>/dev/null && \
       grep -q 'baseFieldDefinitions' "$f" 2>/dev/null; then
        ENTITY_FILES+=("$f")
    fi
done < <(find -L "$MODULES_DIR" -name "*.php" -path "*/Entity/*" 2>/dev/null | sort)

if [[ ${#ENTITY_FILES[@]} -eq 0 ]]; then
    echo "  base-fields: No entity files with baseFieldDefinitions found"
    exit 0
fi

TOTAL_ENTITIES=0
TOTAL_FIELDS=0

# --- Summary table header ---
SUMMARY_FILE="$STRUCTURAL_DIR/base-fields.md"
SUMMARY_TMP=$(mktemp)
trap 'rm -f "$SUMMARY_TMP"' EXIT
cat > "$SUMMARY_TMP" << 'HEADER'
# Base Field Registry
<!-- Auto-generated by generate-base-fields.sh — do not edit manually -->

| Entity Type | Kind | Base Fields | References | Lists | Computed | Schema File |
|-------------|------|-------------|------------|-------|----------|-------------|
HEADER

# Associative array for patching entities.md
declare -A BASE_FIELD_COUNTS

# --- Process each entity file ---

for php_file in "${ENTITY_FILES[@]}"; do
    REL_PATH="${php_file#$PROJECT_DIR/}"
    MODULE=$(echo "$REL_PATH" | sed -E 's#^(web|www)/modules/(custom|contrib)/([^/]+)/.*#\3#; s#^modules/(custom|contrib)/([^/]+)/.*#\2#')
    [[ "$MODULE" == *"/"* ]] && MODULE="(unknown)"

    # --- Pass 1: Entity metadata from PHP 8 attributes ---

    ENTITY_ID=""
    ENTITY_KIND=""
    BASE_TABLE=""
    DATA_TABLE=""
    ADMIN_PERMISSION=""

    # Determine entity kind
    if grep -qE '#\[ContentEntityType' "$php_file" 2>/dev/null; then
        ENTITY_KIND="Content"
    elif grep -qE '#\[ConfigEntityType' "$php_file" 2>/dev/null; then
        ENTITY_KIND="Config"
    fi

    # Extract attribute block using awk (mawk-compatible, no capture groups)
    ATTR_DATA=$(awk '
    /^#\[(Content|Config)EntityType\(/ {
        in_attr = 1
        depth = 0
        line = $0
        for (i = 1; i <= length(line); i++) {
            c = substr(line, i, 1)
            if (c == "(" || c == "[") depth++
            if (c == ")" || c == "]") depth--
        }
        if (depth <= 0) { in_attr = 0 }
        print
        next
    }
    in_attr {
        line = $0
        for (i = 1; i <= length(line); i++) {
            c = substr(line, i, 1)
            if (c == "(" || c == "[") depth++
            if (c == ")" || c == "]") depth--
        }
        print
        if (depth <= 0) { in_attr = 0 }
    }
    ' "$php_file" 2>/dev/null)

    # Extract metadata using shell grep/sed (avoids mawk capture group limitations)
    ENTITY_ID=$(extract_sq_val "id" "$ATTR_DATA")
    [[ -z "$ENTITY_ID" ]] && ENTITY_ID=$(extract_dq_val "id" "$ATTR_DATA")
    [[ -z "$ENTITY_ID" ]] && continue

    BASE_TABLE=$(extract_sq_val "base_table" "$ATTR_DATA")
    [[ -z "$BASE_TABLE" ]] && BASE_TABLE=$(extract_dq_val "base_table" "$ATTR_DATA")

    DATA_TABLE=$(extract_sq_val "data_table" "$ATTR_DATA")
    [[ -z "$DATA_TABLE" ]] && DATA_TABLE=$(extract_dq_val "data_table" "$ATTR_DATA")

    ADMIN_PERMISSION=$(extract_sq_val "admin_permission" "$ATTR_DATA")
    [[ -z "$ADMIN_PERMISSION" ]] && ADMIN_PERMISSION=$(extract_dq_val "admin_permission" "$ATTR_DATA")

    # Extract entity_keys block and parse key => value pairs
    EK_JSON="{"
    EK_FIRST=true
    ENTITY_KEYS_BLOCK=$(echo "$ATTR_DATA" | awk '
    /entity_keys:/ { in_keys = 1; next }
    in_keys && /\]/ { in_keys = 0 }
    in_keys { print }
    ')
    while IFS= read -r ek_line; do
        [[ -z "$ek_line" ]] && continue
        key=$(echo "$ek_line" | grep -oE "'[a-z_]+'" | head -1 | tr -d "'")
        val=$(echo "$ek_line" | sed "s/.*=>[[:space:]]*//" | grep -oE "'[a-z_]+'" | head -1 | tr -d "'")
        if [[ -n "$key" && -n "$val" ]]; then
            [[ "$EK_FIRST" == true ]] && EK_FIRST=false || EK_JSON="$EK_JSON, "
            EK_JSON="$EK_JSON\"$key\": \"$val\""
        fi
    done <<< "$ENTITY_KEYS_BLOCK"
    EK_JSON="$EK_JSON}"

    # --- Pass 2: Base fields from baseFieldDefinitions() ---

    HAS_OWNER=false
    if grep -q 'ownerBaseFieldDefinitions' "$php_file" 2>/dev/null; then
        HAS_OWNER=true
    fi

    # Use awk to parse the baseFieldDefinitions method (mawk-compatible: no capture groups)
    FIELDS_JSON=$(awk '
    BEGIN {
        in_method = 0
        field_name = ""
        field_type = ""
        field_label = ""
        field_desc = ""
        field_required = ""
        field_default = ""
        field_cardinality = ""
        field_computed = ""
        field_target_type = ""
        field_target_bundles = ""
        first_field = 1
        brace_depth = 0

        setting_max_length = ""
        setting_min = ""
        setting_max = ""
        setting_datetime_type = ""
        setting_allowed_values = ""
    }

    function extract_sq(s,    tmp) {
        # Extract first single-quoted value from string
        tmp = s
        sub(/.*\047/, "", tmp)  # remove up to first single quote
        sub(/\047.*/, "", tmp)  # remove from next single quote
        return tmp
    }

    function extract_paren(s,    tmp) {
        # Extract content between ( and )
        tmp = s
        sub(/.*\(/, "", tmp)
        sub(/\).*/, "", tmp)
        return tmp
    }

    function emit_field() {
        if (field_name == "") return
        if (!first_field) printf ","
        first_field = 0

        printf "\n    \"%s\": {\n", field_name
        printf "      \"type\": \"%s\"", field_type

        if (field_label != "") printf ",\n      \"label\": \"%s\"", field_label
        if (field_desc != "") printf ",\n      \"description\": \"%s\"", field_desc

        if (field_required == "TRUE" || field_required == "true") {
            printf ",\n      \"required\": true"
        } else if (field_required == "FALSE" || field_required == "false") {
            printf ",\n      \"required\": false"
        }

        if (field_cardinality != "") {
            if (field_cardinality ~ /CARDINALITY_UNLIMITED/) {
                printf ",\n      \"cardinality\": -1"
            } else {
                printf ",\n      \"cardinality\": %s", field_cardinality
            }
        } else {
            printf ",\n      \"cardinality\": 1"
        }

        if (field_default != "") {
            if (field_default == "TRUE" || field_default == "true") {
                printf ",\n      \"default_value\": true"
            } else if (field_default == "FALSE" || field_default == "false") {
                printf ",\n      \"default_value\": false"
            } else if (field_default ~ /^[0-9]+$/) {
                printf ",\n      \"default_value\": %s", field_default
            } else {
                printf ",\n      \"default_value\": \"%s\"", field_default
            }
        }

        if (field_computed == "TRUE" || field_computed == "true") {
            printf ",\n      \"computed\": true"
        }

        if (field_target_type != "") {
            printf ",\n      \"target_type\": \"%s\"", field_target_type
        }

        if (field_target_bundles != "") {
            printf ",\n      \"target_bundles\": [%s]", field_target_bundles
        }

        # Settings object
        has_settings = 0
        settings_str = ""
        if (setting_max_length != "") {
            settings_str = settings_str "\"max_length\": " setting_max_length
            has_settings = 1
        }
        if (setting_min != "") {
            if (has_settings) settings_str = settings_str ", "
            settings_str = settings_str "\"min\": " setting_min
            has_settings = 1
        }
        if (setting_max != "") {
            if (has_settings) settings_str = settings_str ", "
            settings_str = settings_str "\"max\": " setting_max
            has_settings = 1
        }
        if (setting_datetime_type != "") {
            if (has_settings) settings_str = settings_str ", "
            settings_str = settings_str "\"datetime_type\": \"" setting_datetime_type "\""
            has_settings = 1
        }
        if (setting_allowed_values != "") {
            if (has_settings) settings_str = settings_str ", "
            settings_str = settings_str "\"allowed_values\": [" setting_allowed_values "]"
            has_settings = 1
        }
        if (has_settings) {
            printf ",\n      \"settings\": {%s}", settings_str
        }

        printf "\n    }"

        # Reset
        field_name = ""
        field_type = ""
        field_label = ""
        field_desc = ""
        field_required = ""
        field_default = ""
        field_cardinality = ""
        field_computed = ""
        field_target_type = ""
        field_target_bundles = ""
        setting_max_length = ""
        setting_min = ""
        setting_max = ""
        setting_datetime_type = ""
        setting_allowed_values = ""
    }

    # Detect baseFieldDefinitions method start
    /function baseFieldDefinitions/ {
        in_method = 1
        brace_depth = 0
        next
    }

    !in_method { next }

    # Track brace depth for method boundary
    {
        for (i = 1; i <= length($0); i++) {
            c = substr($0, i, 1)
            if (c == "{") brace_depth++
            if (c == "}") brace_depth--
        }
        if (brace_depth < 0) {
            emit_field()
            exit
        }
    }

    # New field: $fields['"'"'name'"'"'] = BaseFieldDefinition::create('"'"'type'"'"')
    /\$fields\[/ && /BaseFieldDefinition::create/ {
        emit_field()

        # Extract field name: text between $fields[ single-quotes ]
        tmp = $0
        sub(/.*\$fields\[\047/, "", tmp)
        sub(/\047\].*/, "", tmp)
        if (tmp != $0) {
            field_name = tmp
        } else {
            # Try double quotes
            tmp = $0
            sub(/.*\$fields\["/, "", tmp)
            sub(/".*/, "", tmp)
            if (tmp != $0) field_name = tmp
        }

        # Extract field type from BaseFieldDefinition::create('"'"'type'"'"')
        tmp = $0
        sub(/.*BaseFieldDefinition::create\(\047/, "", tmp)
        sub(/\047\).*/, "", tmp)
        if (tmp != $0) {
            field_type = tmp
        } else {
            tmp = $0
            sub(/.*BaseFieldDefinition::create\("/, "", tmp)
            sub(/".*/, "", tmp)
            if (tmp != $0) field_type = tmp
        }
        next
    }

    # return $fields; — end of method
    /return \$fields;/ {
        emit_field()
        exit
    }

    # Skip display options and display configurable (UI-only)
    /->setDisplayOptions/ || /->setDisplayConfigurable/ { next }

    # ->setLabel(new TranslatableMarkup('"'"'Label'"'"'))
    /->setLabel/ && /TranslatableMarkup/ {
        tmp = $0
        # Try single-quoted TranslatableMarkup argument
        if (tmp ~ /TranslatableMarkup\(\047/) {
            sub(/.*TranslatableMarkup\(\047/, "", tmp)
            sub(/\047\).*/, "", tmp)
            field_label = tmp
        } else if (tmp ~ /TranslatableMarkup\("/) {
            sub(/.*TranslatableMarkup\("/, "", tmp)
            sub(/".*/, "", tmp)
            field_label = tmp
        }
        next
    }

    # ->setDescription(new TranslatableMarkup('"'"'Desc'"'"'))
    /->setDescription/ && /TranslatableMarkup/ {
        tmp = $0
        if (tmp ~ /TranslatableMarkup\(\047/) {
            sub(/.*TranslatableMarkup\(\047/, "", tmp)
            sub(/\047\).*/, "", tmp)
            field_desc = tmp
        } else if (tmp ~ /TranslatableMarkup\("/) {
            sub(/.*TranslatableMarkup\("/, "", tmp)
            sub(/".*/, "", tmp)
            field_desc = tmp
        }
        next
    }

    # ->setRequired(TRUE|FALSE)
    /->setRequired\(/ {
        tmp = $0
        sub(/.*->setRequired\(/, "", tmp)
        sub(/\).*/, "", tmp)
        gsub(/[[:space:]]/, "", tmp)
        field_required = tmp
        next
    }

    # ->setDefaultValue(...)
    /->setDefaultValue\(/ {
        tmp = $0
        sub(/.*->setDefaultValue\(/, "", tmp)
        sub(/\).*/, "", tmp)
        gsub(/^\047|\047$/, "", tmp)
        gsub(/^"|"$/, "", tmp)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", tmp)
        field_default = tmp
        next
    }

    # ->setCardinality(...)
    /->setCardinality\(/ {
        tmp = $0
        sub(/.*->setCardinality\(/, "", tmp)
        sub(/\).*/, "", tmp)
        gsub(/[[:space:]]/, "", tmp)
        field_cardinality = tmp
        next
    }

    # ->setComputed(TRUE)
    /->setComputed\(/ {
        tmp = $0
        sub(/.*->setComputed\(/, "", tmp)
        sub(/\).*/, "", tmp)
        gsub(/[[:space:]]/, "", tmp)
        field_computed = tmp
        next
    }

    # ->setSetting('"'"'key'"'"', value)
    /->setSetting\(/ {
        # target_type
        if ($0 ~ /\047target_type\047/) {
            tmp = $0
            # Get value after comma: , '"'"'value'"'"')
            sub(/.*,[ ]*\047/, "", tmp)
            sub(/\047\).*/, "", tmp)
            field_target_type = tmp
            next
        }
        # max_length
        if ($0 ~ /\047max_length\047/) {
            tmp = $0
            sub(/.*,[ ]*/, "", tmp)
            sub(/\).*/, "", tmp)
            gsub(/[^0-9]/, "", tmp)
            setting_max_length = tmp
            next
        }
        # min
        if ($0 ~ /\047min\047/) {
            tmp = $0
            sub(/.*,[ ]*/, "", tmp)
            sub(/\).*/, "", tmp)
            gsub(/[^0-9.]/, "", tmp)
            setting_min = tmp
            next
        }
        # max (careful not to match max_length)
        if ($0 ~ /\047max\047/) {
            tmp = $0
            sub(/.*,[ ]*/, "", tmp)
            sub(/\).*/, "", tmp)
            gsub(/[^0-9.]/, "", tmp)
            setting_max = tmp
            next
        }
        # datetime_type
        if ($0 ~ /\047datetime_type\047/) {
            tmp = $0
            sub(/.*,[ ]*\047/, "", tmp)
            sub(/\047\).*/, "", tmp)
            setting_datetime_type = tmp
            next
        }
        # allowed_values — multi-line array
        if ($0 ~ /\047allowed_values\047/) {
            av_buf = $0
            while ($0 !~ /\]\)/ && (getline > 0)) {
                av_buf = av_buf "\n" $0
            }
            # Extract keys: find lines with 'key' => pattern
            av_result = ""
            n = split(av_buf, av_lines, "\n")
            for (i = 1; i <= n; i++) {
                if (av_lines[i] ~ /\047[^\047]+\047[[:space:]]*=>/) {
                    tmp = av_lines[i]
                    # Remove everything after =>
                    sub(/[[:space:]]*=>.*/, "", tmp)
                    # Remove everything before the last single quote pair
                    gsub(/^[[:space:]]+/, "", tmp)
                    # Now tmp should be like 'key' - extract content
                    gsub(/.*\047/, "", tmp)
                    # Wait, that removes too much. Re-approach:
                    tmp = av_lines[i]
                    sub(/[[:space:]]*=>.*/, "", tmp)
                    gsub(/^[[:space:]]+/, "", tmp)
                    # tmp is now 'key' — strip quotes
                    gsub(/\047/, "", tmp)
                    gsub(/^[[:space:]]+|[[:space:]]+$/, "", tmp)
                    if (tmp != "") {
                        if (av_result != "") av_result = av_result ", "
                        av_result = av_result "\"" tmp "\""
                    }
                }
            }
            setting_allowed_values = av_result
            next
        }
        # handler_settings with target_bundles
        if ($0 ~ /\047handler_settings\047/) {
            hs_buf = $0
            while ($0 !~ /\]\)/ && (getline > 0)) {
                hs_buf = hs_buf "\n" $0
            }
            if (hs_buf ~ /target_bundles/) {
                tb_result = ""
                n = split(hs_buf, lines, "\n")
                in_bundles = 0
                for (i = 1; i <= n; i++) {
                    if (lines[i] ~ /target_bundles/) { in_bundles = 1; continue }
                    if (in_bundles) {
                        if (lines[i] ~ /\]/) { in_bundles = 0; continue }
                        if (lines[i] ~ /\047/) {
                            tmp = lines[i]
                            sub(/.*\047/, "", tmp)
                            sub(/\047.*/, "", tmp)
                            if (tmp != "" && tmp != lines[i]) {
                                if (tb_result != "") tb_result = tb_result ", "
                                tb_result = tb_result "\"" tmp "\""
                            }
                        }
                    }
                }
                field_target_bundles = tb_result
            }
            next
        }
    }
    ' "$php_file" 2>/dev/null)

    # Count fields and categories (use heredoc to avoid temp files — plugin runs in read-only sandbox)
    field_count=$(echo "$FIELDS_JSON" | grep -c '"type":' || true)
    ref_count=$(echo "$FIELDS_JSON" | grep -c '"target_type":' || true)
    list_count=$(echo "$FIELDS_JSON" | grep -c '"allowed_values":' || true)
    computed_count=$(echo "$FIELDS_JSON" | grep -c '"computed": true' || true)
    # Default to 0 if empty
    [[ -z "$field_count" ]] && field_count=0
    [[ -z "$ref_count" ]] && ref_count=0
    [[ -z "$list_count" ]] && list_count=0
    [[ -z "$computed_count" ]] && computed_count=0

    [[ "$field_count" -eq 0 ]] && continue

    # --- Write JSON schema ---
    JSON_FILE="$SCHEMA_DIR/${ENTITY_ID}.base-fields.json"

    {
        printf '{\n'
        printf '  "entity_type": "%s",\n' "$ENTITY_ID"
        printf '  "entity_kind": "%s",\n' "$ENTITY_KIND"

        [[ -n "$BASE_TABLE" ]] && printf '  "base_table": "%s",\n' "$BASE_TABLE"
        [[ -n "$DATA_TABLE" ]] && printf '  "data_table": "%s",\n' "$DATA_TABLE"

        printf '  "entity_keys": %s,\n' "$EK_JSON"

        [[ -n "$ADMIN_PERMISSION" ]] && printf '  "admin_permission": "%s",\n' "$(json_escape "$ADMIN_PERMISSION")"

        printf '  "has_owner": %s,\n' "$HAS_OWNER"
        printf '  "base_fields": {%s\n  },\n' "$FIELDS_JSON"
        printf '  "field_count": %d,\n' "$field_count"
        printf '  "ref_count": %d,\n' "$ref_count"
        printf '  "list_count": %d,\n' "$list_count"
        printf '  "computed_count": %d\n' "$computed_count"
        printf '}\n'
    } > "$JSON_FILE"

    # --- Summary table row ---
    echo "| \`$ENTITY_ID\` | $ENTITY_KIND | $field_count | $ref_count | $list_count | $computed_count | \`schemas/${ENTITY_ID}.base-fields.json\` |" >> "$SUMMARY_TMP"

    BASE_FIELD_COUNTS["$ENTITY_ID"]="$field_count"
    TOTAL_FIELDS=$((TOTAL_FIELDS + field_count))
    ((TOTAL_ENTITIES++)) || true
done

# --- Summary footer ---
{
    echo ""
    echo "---"
    echo "**Total entities**: $TOTAL_ENTITIES"
    echo "**Total base fields**: $TOTAL_FIELDS"
    echo "**Generated**: $(date -Iseconds)"
    echo ""
    echo "**Known limitations:**"
    echo "- Fields from \`parent::baseFieldDefinitions()\` (\`id\`, \`uuid\`, \`langcode\`) are implicit — not enumerated."
    echo "- Config entities without \`baseFieldDefinitions()\` are skipped."
    echo "- \`setDisplayOptions\`/\`setDisplayConfigurable\` are excluded (UI-only metadata)."
} >> "$SUMMARY_TMP"

mv "$SUMMARY_TMP" "$SUMMARY_FILE"

# --- Patch entities.md: update Fields column with base+config counts ---
# Only if entities.md exists AND has a Fields column already (from entity-schemas)
if [[ -f "$ENTITIES_FILE" ]] && grep -q "| Fields |" "$ENTITIES_FILE" 2>/dev/null; then
    PATCHED_FILE="${ENTITIES_FILE}.tmp"
    > "$PATCHED_FILE"

    while IFS= read -r line; do
        # Data rows: look for entity ID in column 3
        if echo "$line" | grep -qE '^\| .+ \| `[a-z_][a-z_0-9]*`' 2>/dev/null; then
            entity_id=$(echo "$line" | awk -F'|' '{
                v=$3; gsub(/^[[:space:]]*`|`[[:space:]]*$/, "", v); print v
            }')

            base_fc="${BASE_FIELD_COUNTS[$entity_id]:-0}"
            if [[ "$base_fc" -gt 0 ]]; then
                # Get current Fields column value (column 6 in the 7-column table)
                current_fields=$(echo "$line" | awk -F'|' '{ v=$6; gsub(/^[[:space:]]+|[[:space:]]+$/, "", v); print v }')

                if [[ "$current_fields" == "-" ]]; then
                    new_fields="$base_fc"
                elif [[ "$current_fields" =~ ^[0-9]+ ]]; then
                    config_fc="${current_fields%% *}"
                    new_fields="${base_fc}+${config_fc}"
                else
                    new_fields="${base_fc}+${current_fields}"
                fi

                # Replace the Fields column value
                echo "$line" | awk -F'|' -v nf=" $new_fields " '{
                    for(i=1; i<=5; i++) printf "%s|", $i
                    printf "%s", nf
                    for(i=7; i<=NF; i++) {
                        if (i < NF) printf "|%s", $i
                        else printf "|"
                    }
                    printf "\n"
                }' >> "$PATCHED_FILE"
            else
                echo "$line" >> "$PATCHED_FILE"
            fi
        else
            echo "$line" >> "$PATCHED_FILE"
        fi
    done < "$ENTITIES_FILE"

    mv "$PATCHED_FILE" "$ENTITIES_FILE"
fi

echo "  base-fields: $TOTAL_ENTITIES entities, $TOTAL_FIELDS base fields"
