#!/bin/bash
# generate-hook-registry.sh - Parse .module files and PHP #[Hook] attributes
# Output: docs/semantic/structural/hooks.md
# Finds procedural hooks (MODULENAME_hookname) and OOP hooks (#[Hook('name')])
set -e

PROJECT_DIR="${1:-${CLAUDE_PROJECT_DIR:-$(pwd)}}"
STRUCTURAL_DIR="$PROJECT_DIR/docs/semantic/structural"
OUTPUT="$STRUCTURAL_DIR/hooks.md"

TMPOUT=$(mktemp)
trap 'rm -f "$TMPOUT"' EXIT

mkdir -p "$STRUCTURAL_DIR"

# Start output
cat > "$TMPOUT" << 'HEADER'
# Hook Registry
<!-- Auto-generated by generate-hook-registry.sh — do not edit manually -->

| Hook Name | Implementation | Type | File | Module |
|-----------|---------------|------|------|--------|
HEADER

TOTAL=0

# --- Procedural hooks from *.module and *.install files ---

MODULE_FILES=()
for search_dir in "$PROJECT_DIR/web/modules/custom" "$PROJECT_DIR/www/modules/custom" "$PROJECT_DIR/modules/custom" "$PROJECT_DIR/web/modules/contrib" "$PROJECT_DIR/www/modules/contrib"; do
    while IFS= read -r f; do
        MODULE_FILES+=("$f")
    done < <(find -L "$search_dir" \( -name "*.module" -o -name "*.install" -o -name "*.profile" \) 2>/dev/null)
    if [[ ${#MODULE_FILES[@]} -gt 0 && "$search_dir" == *"/custom" ]]; then
        break
    fi
done

for mod_file in "${MODULE_FILES[@]}"; do
    # Derive module name from filename (strip .module, .install, or .profile)
    MODULE=$(basename "$mod_file" | sed -E 's/\.(module|install|profile)$//')
    REL_PATH="${mod_file#$PROJECT_DIR/}"

    # Determine file type for the Type column
    FILE_TYPE="procedural"
    case "$mod_file" in
        *.install) FILE_TYPE="install" ;;
        *.profile) FILE_TYPE="profile" ;;
    esac

    # Find function declarations that match MODULENAME_hookname pattern
    # Drupal convention: function modulename_hook_name(
    while IFS= read -r line; do
        # Extract function name
        FUNC_NAME=$(echo "$line" | grep -oE "function ${MODULE}_[a-zA-Z0-9_]+" | sed 's/^function //')
        if [[ -n "$FUNC_NAME" ]]; then
            # Derive hook name by removing module prefix
            HOOK_NAME=$(echo "$FUNC_NAME" | sed "s/^${MODULE}_//")
            echo "| \`$HOOK_NAME\` | \`$FUNC_NAME()\` | $FILE_TYPE | \`$REL_PATH\` | $MODULE |" >> "$TMPOUT"
            ((TOTAL++)) || true
        fi
    done < <(grep -nE "^function ${MODULE}_[a-zA-Z0-9_]+\(" "$mod_file" 2>/dev/null)
done

# --- OOP hooks from #[Hook('name')] attributes (Drupal 11+) ---

PHP_FILES=()
for search_dir in "$PROJECT_DIR/web/modules/custom" "$PROJECT_DIR/www/modules/custom" "$PROJECT_DIR/modules/custom"; do
    while IFS= read -r f; do
        PHP_FILES+=("$f")
    done < <(find -L "$search_dir" -name "*.php" 2>/dev/null)
    if [[ ${#PHP_FILES[@]} -gt 0 ]]; then
        break
    fi
done

for php_file in "${PHP_FILES[@]}"; do
    REL_PATH="${php_file#$PROJECT_DIR/}"

    # Derive module from path: web/modules/custom/MODULE_NAME/src/... or www/modules/custom/...
    MODULE=$(echo "$REL_PATH" | sed -E 's#^(web|www)/modules/(custom|contrib)/([^/]+)/.*#\3#; s#^modules/(custom|contrib)/([^/]+)/.*#\2#')
    [[ "$MODULE" == *"/"* ]] && MODULE="(unknown)"

    # Find #[Hook('hook_name')] or #[Hook("hook_name")] attributes
    while IFS= read -r line; do
        # Extract hook name from attribute
        HOOK_NAME=$(echo "$line" | grep -oE "#\[Hook\(['\"]([^'\"]+)['\"]\)" | sed -E "s/#\[Hook\(['\"]([^'\"]+)['\"]\)/\1/")
        if [[ -n "$HOOK_NAME" ]]; then
            # Try to find the class name from the file
            CLASS_NAME=$(grep -E '^\s*class\s+[A-Z]' "$php_file" 2>/dev/null | head -1 | grep -oE 'class\s+[A-Za-z0-9_]+' | sed 's/class //')
            IMPL="${CLASS_NAME:-"(class)"}"
            echo "| \`$HOOK_NAME\` | \`$IMPL\` | attribute | \`$REL_PATH\` | $MODULE |" >> "$TMPOUT"
            ((TOTAL++)) || true
        fi
    done < <(grep -n '#\[Hook(' "$php_file" 2>/dev/null)
done

# Footer
echo "" >> "$TMPOUT"
echo "---" >> "$TMPOUT"
echo "**Total hook implementations**: $TOTAL" >> "$TMPOUT"
echo "**Module files scanned**: ${#MODULE_FILES[@]}" >> "$TMPOUT"
echo "**PHP files scanned for attributes**: ${#PHP_FILES[@]}" >> "$TMPOUT"
echo "**Generated**: $(date -Iseconds)" >> "$TMPOUT"

mv "$TMPOUT" "$OUTPUT"
echo "  hooks.md: $TOTAL hooks from ${#MODULE_FILES[@]} .module/.install/.profile + ${#PHP_FILES[@]} .php files"
