#!/bin/bash
# generate-service-graph.sh - Parse *.services.yml to build service dependency graph
# Output: docs/semantic/structural/services.md
# Note: yq improves accuracy if available, but grep/sed parsing works without it.
set -e

PROJECT_DIR="${1:-${CLAUDE_PROJECT_DIR:-$(pwd)}}"
STRUCTURAL_DIR="$PROJECT_DIR/docs/semantic/structural"
OUTPUT="$STRUCTURAL_DIR/services.md"

TMPOUT=$(mktemp)
trap 'rm -f "$TMPOUT"' EXIT

mkdir -p "$STRUCTURAL_DIR"

# Collect services.yml files (custom modules first, then contrib)
# Supports web/, www/, and top-level modules/ docroot layouts.
SERVICE_FILES=()
for search_dir in "$PROJECT_DIR/web/modules/custom" "$PROJECT_DIR/www/modules/custom" "$PROJECT_DIR/modules/custom"; do
    while IFS= read -r f; do
        SERVICE_FILES+=("$f")
    done < <(find -L "$search_dir" -name "*.services.yml" 2>/dev/null)
    if [[ ${#SERVICE_FILES[@]} -gt 0 ]]; then
        break
    fi
done

# Include contrib as fallback if no custom modules found
if [[ ${#SERVICE_FILES[@]} -eq 0 ]]; then
    for search_dir in "$PROJECT_DIR/web/modules/contrib" "$PROJECT_DIR/www/modules/contrib"; do
        while IFS= read -r f; do
            SERVICE_FILES+=("$f")
        done < <(find -L "$search_dir" -name "*.services.yml" 2>/dev/null)
        if [[ ${#SERVICE_FILES[@]} -gt 0 ]]; then
            break
        fi
    done
fi

# Start output
cat > "$TMPOUT" << 'HEADER'
# Service Graph
<!-- Auto-generated by generate-service-graph.sh — do not edit manually -->

| Service ID | Class | Dependencies | Module | Tags |
|------------|-------|-------------|--------|------|
HEADER

TOTAL=0

for svc_file in "${SERVICE_FILES[@]}"; do
    # Derive module name from file path
    MODULE=$(basename "$svc_file" .services.yml)
    REL_PATH="${svc_file#$PROJECT_DIR/}"

    # Parse services.yml using grep/sed state machine
    # State: tracking current service ID, class, arguments, tags
    CURRENT_ID=""
    CURRENT_CLASS=""
    CURRENT_ARGS=""
    CURRENT_TAGS=""
    IN_TAGS=0
    IN_ARGUMENTS=0
    IN_SERVICES=0

    flush_service() {
        if [[ -n "$CURRENT_ID" && -n "$CURRENT_CLASS" ]]; then
            # Clean up arguments: extract service references (@service.name)
            DEPS=$(echo "$CURRENT_ARGS" | grep -oE '@[a-z_][a-z_.]*' | tr '\n' ', ' | sed 's/,$//' | sed 's/^,//')
            if [[ -z "$DEPS" ]]; then
                DEPS="-"
            fi
            TAGS_OUT="${CURRENT_TAGS:-"-"}"
            echo "| \`$CURRENT_ID\` | \`$CURRENT_CLASS\` | $DEPS | $MODULE | $TAGS_OUT |" >> "$TMPOUT"
            ((TOTAL++)) || true
        fi
        CURRENT_ID=""
        CURRENT_CLASS=""
        CURRENT_ARGS=""
        CURRENT_TAGS=""
        IN_TAGS=0
        IN_ARGUMENTS=0
    }

    while IFS= read -r line; do
        # Skip comments and empty lines
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${line// }" ]] && continue

        # Detect service ID: exactly 2-space indent, ends with colon, must be inside services: block
        if [[ "$IN_SERVICES" -eq 1 ]] && [[ "$line" =~ ^[[:space:]]{2}[a-zA-Z_][a-zA-Z0-9_.]*:[[:space:]]*$ ]] && ! [[ "$line" =~ ^[[:space:]]{4} ]]; then
            flush_service
            CURRENT_ID=$(echo "$line" | sed 's/^[[:space:]]*//' | sed 's/:[[:space:]]*$//')
            IN_TAGS=0
            IN_ARGUMENTS=0
            continue
        fi

        # Detect top-level keys (0-indent) — only process under "services:"
        if [[ "$line" =~ ^[a-zA-Z_][a-zA-Z0-9_.]*:[[:space:]]*$ ]] && ! [[ "$line" =~ ^[[:space:]] ]]; then
            flush_service
            if [[ "$line" =~ ^services:[[:space:]]*$ ]]; then
                IN_SERVICES=1
            else
                IN_SERVICES=0
            fi
            continue
        fi

        # Properties at 4-space indent
        if [[ -n "$CURRENT_ID" ]]; then
            # Class property
            if [[ "$line" =~ ^[[:space:]]{4}class:[[:space:]]*(.*) ]]; then
                CURRENT_CLASS=$(echo "${BASH_REMATCH[1]}" | sed "s/['\"]//g" | sed 's/[[:space:]]*$//')
                IN_TAGS=0
                IN_ARGUMENTS=0
                continue
            fi

            # Arguments as inline array
            if [[ "$line" =~ ^[[:space:]]{4}arguments:[[:space:]]*\[(.*)\] ]]; then
                CURRENT_ARGS="${BASH_REMATCH[1]}"
                IN_TAGS=0
                IN_ARGUMENTS=0
                continue
            fi

            # Arguments as multi-line list
            if [[ "$line" =~ ^[[:space:]]{4}arguments:[[:space:]]*$ ]]; then
                IN_ARGUMENTS=1
                IN_TAGS=0
                continue
            fi

            # Multi-line argument entry
            if [[ "$IN_ARGUMENTS" -eq 1 ]] && [[ "$line" =~ ^[[:space:]]{6,8}-[[:space:]]*(.*) ]]; then
                CURRENT_ARGS="$CURRENT_ARGS ${BASH_REMATCH[1]}"
                continue
            fi

            # Tags block
            if [[ "$line" =~ ^[[:space:]]{4}tags:[[:space:]]*$ ]]; then
                IN_TAGS=1
                IN_ARGUMENTS=0
                continue
            fi

            # Tag entry: - { name: foo }
            if [[ "$IN_TAGS" -eq 1 ]] && [[ "$line" =~ name:[[:space:]]*([a-z_][a-z_.]*) ]]; then
                if [[ -n "$CURRENT_TAGS" ]]; then
                    CURRENT_TAGS="$CURRENT_TAGS, ${BASH_REMATCH[1]}"
                else
                    CURRENT_TAGS="${BASH_REMATCH[1]}"
                fi
                continue
            fi

            # Any other 4-space property resets multi-line state
            if [[ "$line" =~ ^[[:space:]]{4}[a-z] ]] && ! [[ "$line" =~ ^[[:space:]]{6} ]]; then
                IN_TAGS=0
                IN_ARGUMENTS=0
            fi
        fi
    done < "$svc_file"

    # Flush last service in file
    flush_service
done

# Footer
echo "" >> "$TMPOUT"
echo "---" >> "$TMPOUT"
echo "**Total services**: $TOTAL" >> "$TMPOUT"
echo "**Source files**: ${#SERVICE_FILES[@]} \`*.services.yml\` files" >> "$TMPOUT"
echo "**Generated**: $(date -Iseconds)" >> "$TMPOUT"

mv "$TMPOUT" "$OUTPUT"
echo "  services.md: $TOTAL services from ${#SERVICE_FILES[@]} files"
