#!/bin/bash
# generate-route-map.sh - Parse *.routing.yml to build route map
# Output: docs/semantic/structural/routes.md
# Note: yq improves accuracy if available, but grep/sed parsing works without it.
set -e

PROJECT_DIR="${1:-${CLAUDE_PROJECT_DIR:-$(pwd)}}"
STRUCTURAL_DIR="$PROJECT_DIR/docs/semantic/structural"
OUTPUT="$STRUCTURAL_DIR/routes.md"

TMPOUT=$(mktemp)
trap 'rm -f "$TMPOUT"' EXIT

mkdir -p "$STRUCTURAL_DIR"

# Collect routing.yml files
ROUTE_FILES=()
for search_dir in "$PROJECT_DIR/web/modules/custom" "$PROJECT_DIR/www/modules/custom" "$PROJECT_DIR/modules/custom" "$PROJECT_DIR/web/modules/contrib" "$PROJECT_DIR/www/modules/contrib"; do
    while IFS= read -r f; do
        ROUTE_FILES+=("$f")
    done < <(find -L "$search_dir" -name "*.routing.yml" 2>/dev/null)
    # Stop after custom modules if we found any
    if [[ ${#ROUTE_FILES[@]} -gt 0 && "$search_dir" == *"/custom" ]]; then
        break
    fi
done

# Start output
cat > "$TMPOUT" << 'HEADER'
# Route Map
<!-- Auto-generated by generate-route-map.sh — do not edit manually -->

| Route Name | Path | Controller/Form | Access | Module |
|------------|------|----------------|--------|--------|
HEADER

TOTAL=0

for route_file in "${ROUTE_FILES[@]}"; do
    MODULE=$(basename "$route_file" .routing.yml)

    CURRENT_ROUTE=""
    CURRENT_PATH=""
    CURRENT_CONTROLLER=""
    CURRENT_ACCESS=""

    flush_route() {
        if [[ -n "$CURRENT_ROUTE" && -n "$CURRENT_PATH" ]]; then
            CTRL="${CURRENT_CONTROLLER:-"-"}"
            ACC="${CURRENT_ACCESS:-"-"}"
            echo "| \`$CURRENT_ROUTE\` | \`$CURRENT_PATH\` | \`$CTRL\` | $ACC | $MODULE |" >> "$TMPOUT"
            ((TOTAL++)) || true
        fi
        CURRENT_ROUTE=""
        CURRENT_PATH=""
        CURRENT_CONTROLLER=""
        CURRENT_ACCESS=""
    }

    # Helper: append access requirement (accumulate multiple)
    add_access() {
        if [[ -z "$CURRENT_ACCESS" ]]; then
            CURRENT_ACCESS="$1"
        else
            CURRENT_ACCESS="$CURRENT_ACCESS + $1"
        fi
    }

    while IFS= read -r line; do
        # Skip comments and empty lines
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        [[ -z "${line// }" ]] && continue

        # Route name: top-level key (no leading whitespace or minimal)
        if [[ "$line" =~ ^[a-zA-Z_][a-zA-Z0-9_.]*:[[:space:]]*$ ]]; then
            flush_route
            CURRENT_ROUTE=$(echo "$line" | sed 's/:[[:space:]]*$//')
            continue
        fi

        if [[ -n "$CURRENT_ROUTE" ]]; then
            # Path property
            if [[ "$line" =~ ^[[:space:]]+path:[[:space:]]*[\'\"]*([^\'\"]*)[\'\"]* ]]; then
                CURRENT_PATH=$(echo "$line" | sed "s/^[[:space:]]*path:[[:space:]]*//" | sed "s/['\"]//g" | sed 's/[[:space:]]*$//')
                continue
            fi

            # Controller in defaults block
            if [[ "$line" =~ ^[[:space:]]+_controller:[[:space:]]*(.*) ]]; then
                CURRENT_CONTROLLER=$(echo "${BASH_REMATCH[1]}" | sed "s/['\"]//g" | sed 's/[[:space:]]*$//')
                continue
            fi

            # Form in defaults block
            if [[ "$line" =~ ^[[:space:]]+_form:[[:space:]]*(.*) ]]; then
                CURRENT_CONTROLLER="Form: $(echo "${BASH_REMATCH[1]}" | sed "s/['\"]//g" | sed 's/[[:space:]]*$//')"
                continue
            fi

            # Entity form
            if [[ "$line" =~ ^[[:space:]]+_entity_form:[[:space:]]*(.*) ]]; then
                CURRENT_CONTROLLER="EntityForm: $(echo "${BASH_REMATCH[1]}" | sed "s/['\"]//g" | sed 's/[[:space:]]*$//')"
                continue
            fi

            # Entity list
            if [[ "$line" =~ ^[[:space:]]+_entity_list:[[:space:]]*(.*) ]]; then
                CURRENT_CONTROLLER="EntityList: $(echo "${BASH_REMATCH[1]}" | sed "s/['\"]//g" | sed 's/[[:space:]]*$//')"
                continue
            fi

            # Permission requirement
            if [[ "$line" =~ ^[[:space:]]+_permission:[[:space:]]*(.*) ]]; then
                add_access "permission: $(echo "${BASH_REMATCH[1]}" | sed "s/['\"]//g" | sed 's/[[:space:]]*$//')"
                continue
            fi

            # Role requirement
            if [[ "$line" =~ ^[[:space:]]+_role:[[:space:]]*(.*) ]]; then
                add_access "role: $(echo "${BASH_REMATCH[1]}" | sed "s/['\"]//g" | sed 's/[[:space:]]*$//')"
                continue
            fi

            # Custom access check
            if [[ "$line" =~ ^[[:space:]]+_custom_access:[[:space:]]*(.*) ]]; then
                add_access "custom: $(echo "${BASH_REMATCH[1]}" | sed "s/['\"]//g" | sed 's/[[:space:]]*$//')"
                continue
            fi

            # Entity access check
            if [[ "$line" =~ ^[[:space:]]+_entity_access:[[:space:]]*(.*) ]]; then
                add_access "entity_access: $(echo "${BASH_REMATCH[1]}" | sed "s/['\"]//g" | sed 's/[[:space:]]*$//')"
                continue
            fi

            # Access TRUE (open route)
            if [[ "$line" =~ ^[[:space:]]+_access:[[:space:]]*[\'\"]*TRUE ]]; then
                add_access "public"
                continue
            fi
        fi
    done < "$route_file"

    # Flush last route in file
    flush_route
done

# Footer
echo "" >> "$TMPOUT"
echo "---" >> "$TMPOUT"
echo "**Total routes**: $TOTAL" >> "$TMPOUT"
echo "**Source files**: ${#ROUTE_FILES[@]} \`*.routing.yml\` files" >> "$TMPOUT"
echo "**Generated**: $(date -Iseconds)" >> "$TMPOUT"

mv "$TMPOUT" "$OUTPUT"
echo "  routes.md: $TOTAL routes from ${#ROUTE_FILES[@]} files"
