#!/bin/bash
# generate-permission-registry.sh - Parse *.permissions.yml in custom modules
# Output: docs/semantic/structural/permissions.md
# Finds static permissions declared in YAML (not dynamic permissions_callback).
set -e

PROJECT_DIR="${1:-${CLAUDE_PROJECT_DIR:-$(pwd)}}"
STRUCTURAL_DIR="$PROJECT_DIR/docs/semantic/structural"
OUTPUT="$STRUCTURAL_DIR/permissions.md"

TMPOUT=$(mktemp)
trap 'rm -f "$TMPOUT"' EXIT

mkdir -p "$STRUCTURAL_DIR"

# Start output
cat > "$TMPOUT" << 'HEADER'
# Permission Registry
<!-- Auto-generated by generate-permission-registry.sh — do not edit manually -->

| Permission | Title | Module | Restricted | Description |
|------------|-------|--------|------------|-------------|
HEADER

TOTAL=0
FILE_COUNT=0

# Find permissions.yml files in custom modules
PERM_FILES=()
for search_dir in "$PROJECT_DIR/web/modules/custom" "$PROJECT_DIR/www/modules/custom" "$PROJECT_DIR/modules/custom"; do
    while IFS= read -r f; do
        PERM_FILES+=("$f")
    done < <(find -L "$search_dir" -name "*.permissions.yml" 2>/dev/null)
    if [[ ${#PERM_FILES[@]} -gt 0 ]]; then
        break
    fi
done

for perm_file in "${PERM_FILES[@]}"; do
    [[ -f "$perm_file" ]] || continue
    ((FILE_COUNT++)) || true

    # Derive module name from filename (e.g., timan_holiday.permissions.yml -> timan_holiday)
    MODULE=$(basename "$perm_file" .permissions.yml)

    # awk state machine: parse flat YAML permission blocks
    awk -v module="$MODULE" '
    BEGIN {
        perm = ""
        title = ""
        desc = ""
        restricted = "no"
    }

    # New permission: line at zero indent matching word chars and colon
    /^[a-zA-Z_][a-zA-Z0-9_ ]*:$/ {
        # Emit previous permission if any
        if (perm != "") {
            printf "| `%s` | %s | %s | %s | %s |\n", perm, title, module, restricted, desc
        }
        # Start new permission
        perm = $0
        sub(/:$/, "", perm)
        title = "-"
        desc = "-"
        restricted = "no"
        next
    }

    # Indented lines within a permission block
    perm != "" && /^[[:space:]]+/ {
        line = $0
        # Remove leading whitespace
        gsub(/^[[:space:]]+/, "", line)

        if (line ~ /^title:/) {
            val = line
            sub(/^title:[[:space:]]*/, "", val)
            gsub(/^'\''|'\''$/, "", val)
            gsub(/^"|"$/, "", val)
            title = val
        }
        else if (line ~ /^description:/) {
            val = line
            sub(/^description:[[:space:]]*/, "", val)
            gsub(/^'\''|'\''$/, "", val)
            gsub(/^"|"$/, "", val)
            desc = val
        }
        else if (line ~ /^restrict access:/) {
            val = line
            sub(/^restrict access:[[:space:]]*/, "", val)
            gsub(/[[:space:]]/, "", val)
            if (val == "true" || val == "TRUE" || val == "True") {
                restricted = "yes"
            }
        }
    }

    END {
        # Emit last permission
        if (perm != "") {
            printf "| `%s` | %s | %s | %s | %s |\n", perm, title, module, restricted, desc
        }
    }
    ' "$perm_file" >> "$TMPOUT"

    # Count permissions in this file
    file_perms=$(grep -cE '^[a-zA-Z_][a-zA-Z0-9_ ]*:$' "$perm_file" 2>/dev/null || true)
    file_perms=${file_perms:-0}
    TOTAL=$((TOTAL + file_perms))
done

# Footer
{
    echo ""
    echo "---"
    echo "**Total permissions**: $TOTAL"
    echo "**Permission files**: $FILE_COUNT"
    echo "**Generated**: $(date -Iseconds)"
    echo ""
    echo "**Known limitations:**"
    echo "- Dynamic permissions from \`permission_callbacks\` in \`*.permissions.yml\` are not detected."
    echo "- Only custom modules are scanned."
} >> "$TMPOUT"

mv "$TMPOUT" "$OUTPUT"
echo "  permissions.md: $TOTAL permissions from $FILE_COUNT files"
