#!/bin/bash
# generate-method-index.sh - Index public methods in Service, Controller, Form classes
# Output: docs/semantic/structural/methods.md
# Scans src/Service/, src/Controller/, src/Form/ in custom modules.
# Skips *Interface.php, *Trait.php, and magic methods.
set -e

PROJECT_DIR="${1:-${CLAUDE_PROJECT_DIR:-$(pwd)}}"
STRUCTURAL_DIR="$PROJECT_DIR/docs/semantic/structural"

TMPOUT=$(mktemp)
trap 'rm -f "$TMPOUT"' EXIT
OUTPUT="$STRUCTURAL_DIR/methods.md"

mkdir -p "$STRUCTURAL_DIR"

# --- Collect PHP files by category ---

MODULES_DIR=""
for search_dir in "$PROJECT_DIR/web/modules/custom" "$PROJECT_DIR/www/modules/custom" "$PROJECT_DIR/modules/custom"; do
    if [[ -d "$search_dir" ]]; then
        MODULES_DIR="$search_dir"
        break
    fi
done

if [[ -z "$MODULES_DIR" ]]; then
    echo "  methods.md: No custom modules directory found"
    cat > "$TMPOUT" << 'HEADER'
# Method Index
<!-- Auto-generated by generate-method-index.sh — do not edit manually -->

No custom modules directory found.
HEADER
    mv "$TMPOUT" "$OUTPUT"
    exit 0
fi

# Associative arrays for results per category
declare -a SERVICE_LINES CONTROLLER_LINES FORM_LINES OTHER_LINES

SERVICE_COUNT=0
CONTROLLER_COUNT=0
FORM_COUNT=0
OTHER_COUNT=0
FILES_SCANNED=0

# Process a single PHP file
# Args: $1=file_path $2=category (Service|Controller|Form)
process_php_file() {
    local php_file="$1"
    local category="$2"

    ((FILES_SCANNED++)) || true

    local rel_path="${php_file#$PROJECT_DIR/}"

    # Derive module from path
    local module
    module=$(echo "$rel_path" | sed -E 's#^(web|www)/modules/(custom|contrib)/([^/]+)/.*#\3#; s#^modules/(custom|contrib)/([^/]+)/.*#\2#')
    [[ "$module" == *"/"* ]] && module="(unknown)"

    # Get class name
    local class_name
    class_name=$(grep -E '^\s*(final\s+|abstract\s+)*class\s+[A-Z]' "$php_file" 2>/dev/null | head -1 | grep -oE 'class\s+[A-Za-z0-9_]+' | sed 's/class //')
    [[ -z "$class_name" ]] && return

    # Extract public methods with line numbers
    # Match: public [static] function methodName(
    while IFS= read -r match_line; do
        local line_num method_name is_static return_type

        line_num=$(echo "$match_line" | cut -d: -f1)
        local func_line=$(echo "$match_line" | cut -d: -f2-)

        # Extract method name
        method_name=$(echo "$func_line" | grep -oE 'function\s+[a-zA-Z_][a-zA-Z0-9_]*' | sed 's/function\s*//')
        [[ -z "$method_name" ]] && continue

        # Skip magic methods
        case "$method_name" in
            __construct|__destruct|__toString|__clone|__sleep|__wakeup|__invoke|__debugInfo|__serialize|__unserialize|__set_state|__get|__set|__isset|__unset|__call|__callStatic)
                continue
                ;;
        esac

        # Check static
        is_static=""
        if echo "$func_line" | grep -qE 'static\s+function' 2>/dev/null; then
            is_static="static "
        fi

        # Extract return type - check same line first
        return_type=""
        # Look for ): ReturnType on same line or next few lines
        # First check if closing paren and return type are on same line
        if echo "$func_line" | grep -qE '\)\s*:\s*' 2>/dev/null; then
            return_type=$(echo "$func_line" | sed -E 's/.*\)\s*:\s*//' | sed -E 's/\s*\{.*//' | sed 's/[[:space:]]*$//')
        else
            # Peek next 10 lines for multi-line signatures
            local peek_end=$((line_num + 10))
            local peek_block
            peek_block=$(sed -n "$((line_num+1)),${peek_end}p" "$php_file" 2>/dev/null)
            # Find the line with ) : Type or ): Type
            local ret_line
            ret_line=$(echo "$peek_block" | grep -m1 -E '\)\s*:\s*' 2>/dev/null || true)
            if [[ -n "$ret_line" ]]; then
                return_type=$(echo "$ret_line" | sed -E 's/.*\)\s*:\s*//' | sed -E 's/\s*\{.*//' | sed 's/[[:space:]]*$//')
            fi
        fi

        # Clean up return type
        return_type=$(echo "$return_type" | sed 's/[[:space:]]*{$//' | sed 's/[[:space:]]*$//')
        [[ -z "$return_type" ]] && return_type="-"

        local table_line="| \`$class_name\` | \`${is_static}${method_name}()\` | \`$return_type\` | $module | \`$rel_path\` | $line_num |"

        case "$category" in
            Service)
                SERVICE_LINES+=("$table_line")
                ((SERVICE_COUNT++)) || true
                ;;
            Controller)
                CONTROLLER_LINES+=("$table_line")
                ((CONTROLLER_COUNT++)) || true
                ;;
            Form)
                FORM_LINES+=("$table_line")
                ((FORM_COUNT++)) || true
                ;;
            *)
                OTHER_LINES+=("$table_line")
                ((OTHER_COUNT++)) || true
                ;;
        esac

    done < <(grep -nE '^\s*public\s+(static\s+)?function\s+[a-zA-Z_]' "$php_file" 2>/dev/null)
}

# Find and process files by category
# Primary categories: Service, Controller, Form
# Extended categories: EventSubscriber, Access, Manager, Builder (mapped to "Other")
for category_dir in "Service" "Controller" "Form" "EventSubscriber" "Access" "Manager" "Builder"; do
    local_category="$category_dir"
    # Map extended categories to the "Other" bucket for output
    case "$category_dir" in
        EventSubscriber|Access|Manager|Builder) local_category="$category_dir" ;;
    esac

    while IFS= read -r php_file; do
        bn=$(basename "$php_file")
        # Skip interfaces and traits
        [[ "$bn" == *Interface.php ]] && continue
        [[ "$bn" == *Trait.php ]] && continue

        # Map extended dirs to Other for output grouping
        case "$category_dir" in
            Service|Controller|Form) process_php_file "$php_file" "$category_dir" ;;
            *) process_php_file "$php_file" "$category_dir" ;;
        esac
    done < <(find -L "$MODULES_DIR" -path "*/src/${category_dir}/*.php" 2>/dev/null | sort)
done

# --- Write output ---

cat > "$TMPOUT" << 'HEADER'
# Method Index
<!-- Auto-generated by generate-method-index.sh — do not edit manually -->

HEADER

# Services section
{
    echo "## Services"
    echo ""
    echo "| Service Class | Method | Return Type | Module | File | Line |"
    echo "|---------------|--------|-------------|--------|------|------|"
} >> "$TMPOUT"
for line in "${SERVICE_LINES[@]}"; do
    echo "$line" >> "$TMPOUT"
done

# Controllers section
{
    echo ""
    echo "## Controllers"
    echo ""
    echo "| Controller Class | Method | Return Type | Module | File | Line |"
    echo "|------------------|--------|-------------|--------|------|------|"
} >> "$TMPOUT"
for line in "${CONTROLLER_LINES[@]}"; do
    echo "$line" >> "$TMPOUT"
done

# Forms section
{
    echo ""
    echo "## Forms"
    echo ""
    echo "| Form Class | Method | Return Type | Module | File | Line |"
    echo "|------------|--------|-------------|--------|------|------|"
} >> "$TMPOUT"
for line in "${FORM_LINES[@]}"; do
    echo "$line" >> "$TMPOUT"
done

# Other section (EventSubscriber, Access, Manager, Builder)
if [[ ${#OTHER_LINES[@]} -gt 0 ]]; then
    {
        echo ""
        echo "## Other (EventSubscriber, Access, Manager, Builder)"
        echo ""
        echo "| Class | Method | Return Type | Module | File | Line |"
        echo "|-------|--------|-------------|--------|------|------|"
    } >> "$TMPOUT"
    for line in "${OTHER_LINES[@]}"; do
        echo "$line" >> "$TMPOUT"
    done
fi

# Footer
TOTAL=$((SERVICE_COUNT + CONTROLLER_COUNT + FORM_COUNT + OTHER_COUNT))
{
    echo ""
    echo "---"
    echo "**Total methods**: $TOTAL (Services: $SERVICE_COUNT, Controllers: $CONTROLLER_COUNT, Forms: $FORM_COUNT, Other: $OTHER_COUNT)"
    echo "**PHP files scanned**: $FILES_SCANNED"
    echo "**Generated**: $(date -Iseconds)"
    echo ""
    echo "**Known limitations:**"
    echo "- Private and protected methods excluded by design."
    echo "- Magic methods (\`__construct\`, etc.) excluded."
    echo "- Interface and Trait files excluded."
} >> "$TMPOUT"

mv "$TMPOUT" "$OUTPUT"
echo "  methods.md: $TOTAL methods (svc:$SERVICE_COUNT ctrl:$CONTROLLER_COUNT form:$FORM_COUNT other:$OTHER_COUNT) from $FILES_SCANNED files"
