#!/bin/bash
# generate-entity-map.sh - Parse PHP files for entity type annotations/attributes
# Output: docs/semantic/structural/entities.md
# Detects @ContentEntityType, @ConfigEntityType, #[ContentEntityType], #[ConfigEntityType]
set -e

PROJECT_DIR="${1:-${CLAUDE_PROJECT_DIR:-$(pwd)}}"
STRUCTURAL_DIR="$PROJECT_DIR/docs/semantic/structural"
OUTPUT="$STRUCTURAL_DIR/entities.md"

TMPOUT=$(mktemp)
trap 'rm -f "$TMPOUT"' EXIT

mkdir -p "$STRUCTURAL_DIR"

# Start output
cat > "$TMPOUT" << 'HEADER'
# Entity Map
<!-- Auto-generated by generate-entity-map.sh — do not edit manually -->

| Entity Type | ID | Class | Handlers | Module | File |
|------------|-----|-------|----------|--------|------|
HEADER

TOTAL=0

ENTITY_TYPES="ContentEntityType|ConfigEntityType"

# Collect PHP files
PHP_FILES=()
for search_dir in "$PROJECT_DIR/web/modules/custom" "$PROJECT_DIR/www/modules/custom" "$PROJECT_DIR/modules/custom"; do
    while IFS= read -r f; do
        PHP_FILES+=("$f")
    done < <(find -L "$search_dir" -name "*.php" 2>/dev/null)
    if [[ ${#PHP_FILES[@]} -gt 0 ]]; then
        break
    fi
done

# Fallback to contrib
if [[ ${#PHP_FILES[@]} -eq 0 ]]; then
    for search_dir in "$PROJECT_DIR/web/modules/contrib" "$PROJECT_DIR/www/modules/contrib"; do
        while IFS= read -r f; do
            PHP_FILES+=("$f")
        done < <(find -L "$search_dir" -name "*.php" 2>/dev/null)
        if [[ ${#PHP_FILES[@]} -gt 0 ]]; then
            break
        fi
    done
fi

for php_file in "${PHP_FILES[@]}"; do
    # Quick check: does this file contain entity type declarations?
    if ! grep -qE "@($ENTITY_TYPES)|#\[($ENTITY_TYPES)" "$php_file" 2>/dev/null; then
        continue
    fi

    REL_PATH="${php_file#$PROJECT_DIR/}"
    MODULE=$(echo "$REL_PATH" | sed -E 's#^(web|www)/modules/(custom|contrib)/([^/]+)/.*#\3#; s#^modules/(custom|contrib)/([^/]+)/.*#\2#')
    [[ "$MODULE" == *"/"* ]] && MODULE="(unknown)"

    # Get class name
    CLASS_NAME=$(grep -E '^\s*(final\s+|abstract\s+)*class\s+[A-Z]' "$php_file" 2>/dev/null | head -1 | grep -oE 'class\s+[A-Za-z0-9_]+' | sed 's/class //')
    if [[ -z "$CLASS_NAME" ]]; then
        continue
    fi

    # Determine entity type (Content vs Config)
    ENTITY_KIND=""
    if grep -qE "@ContentEntityType|#\[ContentEntityType" "$php_file" 2>/dev/null; then
        ENTITY_KIND="Content"
    elif grep -qE "@ConfigEntityType|#\[ConfigEntityType" "$php_file" 2>/dev/null; then
        ENTITY_KIND="Config"
    fi

    # Find the annotation/attribute start line
    ANNO_LINE=$(grep -nE "@($ENTITY_TYPES)\(|#\[($ENTITY_TYPES)\(" "$php_file" 2>/dev/null | head -1 | cut -d: -f1)
    if [[ -z "$ANNO_LINE" ]]; then
        continue
    fi

    # Extract annotation block (up to 60 lines after the start)
    ANNO_BLOCK=$(sed -n "${ANNO_LINE},$((ANNO_LINE+60))p" "$php_file" 2>/dev/null)

    # Extract entity ID
    ENTITY_ID=$(echo "$ANNO_BLOCK" | grep -oE "id\s*=\s*['\"][^'\"]*['\"]" | head -1 | sed "s/id\s*=\s*['\"]//;s/['\"]$//")
    if [[ -z "$ENTITY_ID" ]]; then
        # Try named argument style: id: "value"
        ENTITY_ID=$(echo "$ANNO_BLOCK" | grep -oE "id:\s*['\"][^'\"]*['\"]" | head -1 | sed "s/id:[[:space:]]*//" | sed "s/['\"]//g")
    fi
    if [[ -z "$ENTITY_ID" ]]; then
        ENTITY_ID="(unknown)"
    fi

    # Extract handlers — look for common handler keys
    HANDLERS=""
    for handler_key in "list_builder" "form" "views_data" "storage" "access" "route_provider" "translation"; do
        if echo "$ANNO_BLOCK" | grep -qiE "\"$handler_key\"" 2>/dev/null; then
            if [[ -n "$HANDLERS" ]]; then
                HANDLERS="$HANDLERS, $handler_key"
            else
                HANDLERS="$handler_key"
            fi
        fi
    done
    if [[ -z "$HANDLERS" ]]; then
        HANDLERS="-"
    fi

    echo "| $ENTITY_KIND | \`$ENTITY_ID\` | \`$CLASS_NAME\` | $HANDLERS | $MODULE | \`$REL_PATH\` |" >> "$TMPOUT"
    ((TOTAL++)) || true
done

# Footer
echo "" >> "$TMPOUT"
echo "---" >> "$TMPOUT"
echo "**Total entity types**: $TOTAL" >> "$TMPOUT"
echo "**PHP files scanned**: ${#PHP_FILES[@]}" >> "$TMPOUT"
echo "**Generated**: $(date -Iseconds)" >> "$TMPOUT"

mv "$TMPOUT" "$OUTPUT"
echo "  entities.md: $TOTAL entity types from ${#PHP_FILES[@]} PHP files"
