#!/bin/bash
# generate-plugin-registry.sh - Parse PHP files for Drupal plugin annotations/attributes
# Output: docs/semantic/structural/plugins.md
# Detects Block, FieldType, FieldFormatter, FieldWidget, Action, QueueWorker,
# Constraint, and generic plugin patterns.
set -e

PROJECT_DIR="${1:-${CLAUDE_PROJECT_DIR:-$(pwd)}}"
STRUCTURAL_DIR="$PROJECT_DIR/docs/semantic/structural"
OUTPUT="$STRUCTURAL_DIR/plugins.md"

TMPOUT=$(mktemp)
trap 'rm -f "$TMPOUT"' EXIT

mkdir -p "$STRUCTURAL_DIR"

# Start output
cat > "$TMPOUT" << 'HEADER'
# Plugin Registry
<!-- Auto-generated by generate-plugin-registry.sh — do not edit manually -->

| Plugin Type | ID | Class | Module | File |
|------------|-----|-------|--------|------|
HEADER

TOTAL=0

# Known plugin types to search for
PLUGIN_TYPES=(
    "Block"
    "FieldType"
    "FieldFormatter"
    "FieldWidget"
    "Action"
    "QueueWorker"
    "Constraint"
    "ContentEntityType"
    "ConfigEntityType"
    "ViewsField"
    "ViewsFilter"
    "ViewsSort"
    "ViewsArgument"
    "Condition"
    "RulesAction"
    "ResourceBase"
    "RestResource"
)

# Build a regex pattern for all known types
ANNOTATION_PATTERN=$(printf "|%s" "${PLUGIN_TYPES[@]}")
ANNOTATION_PATTERN="${ANNOTATION_PATTERN:1}" # Remove leading |

# Collect PHP files
PHP_FILES=()
for search_dir in "$PROJECT_DIR/web/modules/custom" "$PROJECT_DIR/www/modules/custom" "$PROJECT_DIR/modules/custom"; do
    while IFS= read -r f; do
        PHP_FILES+=("$f")
    done < <(find -L "$search_dir" -name "*.php" 2>/dev/null)
    if [[ ${#PHP_FILES[@]} -gt 0 ]]; then
        break
    fi
done

# Fallback to contrib if no custom modules
if [[ ${#PHP_FILES[@]} -eq 0 ]]; then
    for search_dir in "$PROJECT_DIR/web/modules/contrib" "$PROJECT_DIR/www/modules/contrib"; do
        while IFS= read -r f; do
            PHP_FILES+=("$f")
        done < <(find -L "$search_dir" -name "*.php" 2>/dev/null)
        if [[ ${#PHP_FILES[@]} -gt 0 ]]; then
            break
        fi
    done
fi

for php_file in "${PHP_FILES[@]}"; do
    REL_PATH="${php_file#$PROJECT_DIR/}"

    # Derive module from path
    MODULE=$(echo "$REL_PATH" | sed -E 's#^(web|www)/modules/(custom|contrib)/([^/]+)/.*#\3#; s#^modules/(custom|contrib)/([^/]+)/.*#\2#')
    [[ "$MODULE" == *"/"* ]] && MODULE="(unknown)"

    # Get class name from file
    CLASS_NAME=$(grep -E '^\s*(final\s+|abstract\s+)*class\s+[A-Z]' "$php_file" 2>/dev/null | head -1 | grep -oE 'class\s+[A-Za-z0-9_]+' | sed 's/class //')
    if [[ -z "$CLASS_NAME" ]]; then
        continue
    fi

    # Check for annotation-style plugins: @PluginType(
    while IFS= read -r match_line; do
        PLUGIN_TYPE=$(echo "$match_line" | grep -oE "@($ANNOTATION_PATTERN)\(" | sed 's/@//' | sed 's/($//')
        if [[ -n "$PLUGIN_TYPE" ]]; then
            # Try to extract id from the annotation
            # Look for id = "..." on same or next lines
            LINE_NUM=$(echo "$match_line" | cut -d: -f1)
            PLUGIN_ID=""
            # Search within next 10 lines for id
            PLUGIN_ID=$(sed -n "${LINE_NUM},$((LINE_NUM+10))p" "$php_file" 2>/dev/null | grep -oE 'id\s*=\s*"[^"]*"' | head -1 | sed 's/id\s*=\s*"//' | sed 's/"$//')
            if [[ -z "$PLUGIN_ID" ]]; then
                PLUGIN_ID="(inline)"
            fi
            echo "| $PLUGIN_TYPE | \`$PLUGIN_ID\` | \`$CLASS_NAME\` | $MODULE | \`$REL_PATH\` |" >> "$TMPOUT"
            ((TOTAL++)) || true
        fi
    done < <(grep -nE "@($ANNOTATION_PATTERN)\(" "$php_file" 2>/dev/null)

    # Check for attribute-style plugins: #[PluginType(
    while IFS= read -r match_line; do
        PLUGIN_TYPE=$(echo "$match_line" | grep -oE "#\[($ANNOTATION_PATTERN)\(" | sed 's/#\[//' | sed 's/($//')
        if [[ -n "$PLUGIN_TYPE" ]]; then
            LINE_NUM=$(echo "$match_line" | cut -d: -f1)
            PLUGIN_ID=""
            PLUGIN_ID=$(sed -n "${LINE_NUM},$((LINE_NUM+10))p" "$php_file" 2>/dev/null | grep -oE 'id:\s*['\''"][^'\''\"]*['\''"]' | head -1 | sed "s/id:[[:space:]]*//" | sed "s/['\"]//g")
            if [[ -z "$PLUGIN_ID" ]]; then
                # Try positional first argument: #[Block("my_block",
                PLUGIN_ID=$(sed -n "${LINE_NUM}p" "$php_file" 2>/dev/null | grep -oE "#\[$PLUGIN_TYPE\(['\"][^'\"]*['\"]" | sed "s|#\[$PLUGIN_TYPE(||" | sed "s/['\"]//g")
            fi
            if [[ -z "$PLUGIN_ID" ]]; then
                PLUGIN_ID="(inline)"
            fi
            echo "| $PLUGIN_TYPE | \`$PLUGIN_ID\` | \`$CLASS_NAME\` | $MODULE | \`$REL_PATH\` |" >> "$TMPOUT"
            ((TOTAL++)) || true
        fi
    done < <(grep -nE "#\[($ANNOTATION_PATTERN)\(" "$php_file" 2>/dev/null)
done

# Footer
echo "" >> "$TMPOUT"
echo "---" >> "$TMPOUT"
echo "**Total plugins**: $TOTAL" >> "$TMPOUT"
echo "**PHP files scanned**: ${#PHP_FILES[@]}" >> "$TMPOUT"
echo "**Generated**: $(date -Iseconds)" >> "$TMPOUT"

mv "$TMPOUT" "$OUTPUT"
echo "  plugins.md: $TOTAL plugins from ${#PHP_FILES[@]} PHP files"
